// ─────────────────────────────────────────────────────────────
// GENERATED by BoneProbe emit — DO NOT EDIT BY HAND.
// Signature for the dataset emitted next to it (regenerate both).
// ─────────────────────────────────────────────────────────────
namespace LiveMap.Catalog

open System.Collections.Frozen

module Models =

  [<Literal>]
  val BasePath: string = "assets/kenney_platformer-kit/Models"

  val all: ModelInfo[]

  val byName: FrozenDictionary<string, ModelInfo>

  val tryByName: name: string -> ModelInfo voption
