// ─────────────────────────────────────────────────────────────
// GENERATED by BoneProbe emit — DO NOT EDIT BY HAND.
// Regenerate with:  dotnet run --project BoneProbe -- emit assets/kenney_platformer-kit/Models LiveMap/Catalog/Models.fs --namespace LiveMap.Catalog --base-path assets/kenney_platformer-kit/Models --fsi
// Sources: assets/kenney_platformer-kit/Models/*.glb (153 models)
// ─────────────────────────────────────────────────────────────
namespace LiveMap.Catalog

open System.Collections.Frozen
open System.Collections.Generic

// ModelInfo is hand-defined in this namespace.

module Models =

  [<Literal>]
  let BasePath = "assets/kenney_platformer-kit/Models"

  /// All models baked at compile time (mesh-local extents, sorted by name).
  /// Canonical store: ordered and iterable. The name index is built from it.
  let all: ModelInfo[] = [|
    {
      Name = "arrow"
      Path = "assets/kenney_platformer-kit/Models/arrow"
      SizeX = 0.456f
      SizeY = 0.6f
      SizeZ = 0.142f
    }
    {
      Name = "arrows"
      Path = "assets/kenney_platformer-kit/Models/arrows"
      SizeX = 0.502f
      SizeY = 0.9f
      SizeZ = 0.142f
    }
    {
      Name = "barrel"
      Path = "assets/kenney_platformer-kit/Models/barrel"
      SizeX = 0.518f
      SizeY = 0.476f
      SizeZ = 0.518f
    }
    {
      Name = "block-grass"
      Path = "assets/kenney_platformer-kit/Models/block-grass"
      SizeX = 1.082f
      SizeY = 1.0f
      SizeZ = 1.082f
    }
    {
      Name = "block-grass-corner"
      Path = "assets/kenney_platformer-kit/Models/block-grass-corner"
      SizeX = 1.054f
      SizeY = 1.0f
      SizeZ = 1.054f
    }
    {
      Name = "block-grass-corner-low"
      Path = "assets/kenney_platformer-kit/Models/block-grass-corner-low"
      SizeX = 1.054f
      SizeY = 0.5f
      SizeZ = 1.054f
    }
    {
      Name = "block-grass-corner-overhang"
      Path = "assets/kenney_platformer-kit/Models/block-grass-corner-overhang"
      SizeX = 1.054f
      SizeY = 1.0f
      SizeZ = 1.054f
    }
    {
      Name = "block-grass-corner-overhang-low"
      Path =
        "assets/kenney_platformer-kit/Models/block-grass-corner-overhang-low"
      SizeX = 1.054f
      SizeY = 0.5f
      SizeZ = 1.054f
    }
    {
      Name = "block-grass-curve"
      Path = "assets/kenney_platformer-kit/Models/block-grass-curve"
      SizeX = 2.0f
      SizeY = 1.0f
      SizeZ = 1.0f
    }
    {
      Name = "block-grass-curve-half"
      Path = "assets/kenney_platformer-kit/Models/block-grass-curve-half"
      SizeX = 1.0f
      SizeY = 1.0f
      SizeZ = 1.0f
    }
    {
      Name = "block-grass-curve-low"
      Path = "assets/kenney_platformer-kit/Models/block-grass-curve-low"
      SizeX = 2.0f
      SizeY = 0.5f
      SizeZ = 1.0f
    }
    {
      Name = "block-grass-edge"
      Path = "assets/kenney_platformer-kit/Models/block-grass-edge"
      SizeX = 1.082f
      SizeY = 1.0f
      SizeZ = 1.082f
    }
    {
      Name = "block-grass-hexagon"
      Path = "assets/kenney_platformer-kit/Models/block-grass-hexagon"
      SizeX = 1.1f
      SizeY = 1.0f
      SizeZ = 1.27f
    }
    {
      Name = "block-grass-large"
      Path = "assets/kenney_platformer-kit/Models/block-grass-large"
      SizeX = 2.082f
      SizeY = 1.0f
      SizeZ = 2.082f
    }
    {
      Name = "block-grass-large-slope"
      Path = "assets/kenney_platformer-kit/Models/block-grass-large-slope"
      SizeX = 2.082f
      SizeY = 0.759f
      SizeZ = 2.011f
    }
    {
      Name = "block-grass-large-slope-narrow"
      Path =
        "assets/kenney_platformer-kit/Models/block-grass-large-slope-narrow"
      SizeX = 1.082f
      SizeY = 0.759f
      SizeZ = 2.011f
    }
    {
      Name = "block-grass-large-slope-steep"
      Path = "assets/kenney_platformer-kit/Models/block-grass-large-slope-steep"
      SizeX = 2.082f
      SizeY = 1.217f
      SizeZ = 1.857f
    }
    {
      Name = "block-grass-large-slope-steep-narrow"
      Path =
        "assets/kenney_platformer-kit/Models/block-grass-large-slope-steep-narrow"
      SizeX = 1.082f
      SizeY = 1.217f
      SizeZ = 1.857f
    }
    {
      Name = "block-grass-large-tall"
      Path = "assets/kenney_platformer-kit/Models/block-grass-large-tall"
      SizeX = 2.082f
      SizeY = 2.0f
      SizeZ = 2.082f
    }
    {
      Name = "block-grass-long"
      Path = "assets/kenney_platformer-kit/Models/block-grass-long"
      SizeX = 2.082f
      SizeY = 1.0f
      SizeZ = 1.082f
    }
    {
      Name = "block-grass-low"
      Path = "assets/kenney_platformer-kit/Models/block-grass-low"
      SizeX = 1.082f
      SizeY = 0.5f
      SizeZ = 1.082f
    }
    {
      Name = "block-grass-low-hexagon"
      Path = "assets/kenney_platformer-kit/Models/block-grass-low-hexagon"
      SizeX = 1.1f
      SizeY = 0.5f
      SizeZ = 1.27f
    }
    {
      Name = "block-grass-low-large"
      Path = "assets/kenney_platformer-kit/Models/block-grass-low-large"
      SizeX = 2.082f
      SizeY = 0.5f
      SizeZ = 2.082f
    }
    {
      Name = "block-grass-low-long"
      Path = "assets/kenney_platformer-kit/Models/block-grass-low-long"
      SizeX = 2.082f
      SizeY = 0.5f
      SizeZ = 1.082f
    }
    {
      Name = "block-grass-low-narrow"
      Path = "assets/kenney_platformer-kit/Models/block-grass-low-narrow"
      SizeX = 0.782f
      SizeY = 0.5f
      SizeZ = 0.782f
    }
    {
      Name = "block-grass-narrow"
      Path = "assets/kenney_platformer-kit/Models/block-grass-narrow"
      SizeX = 0.782f
      SizeY = 1.0f
      SizeZ = 0.782f
    }
    {
      Name = "block-grass-overhang-corner"
      Path = "assets/kenney_platformer-kit/Models/block-grass-overhang-corner"
      SizeX = 1.082f
      SizeY = 1.0f
      SizeZ = 1.082f
    }
    {
      Name = "block-grass-overhang-edge"
      Path = "assets/kenney_platformer-kit/Models/block-grass-overhang-edge"
      SizeX = 1.082f
      SizeY = 1.0f
      SizeZ = 1.082f
    }
    {
      Name = "block-grass-overhang-hexagon"
      Path = "assets/kenney_platformer-kit/Models/block-grass-overhang-hexagon"
      SizeX = 1.1f
      SizeY = 1.0f
      SizeZ = 1.27f
    }
    {
      Name = "block-grass-overhang-large"
      Path = "assets/kenney_platformer-kit/Models/block-grass-overhang-large"
      SizeX = 2.082f
      SizeY = 1.0f
      SizeZ = 2.082f
    }
    {
      Name = "block-grass-overhang-large-slope"
      Path =
        "assets/kenney_platformer-kit/Models/block-grass-overhang-large-slope"
      SizeX = 2.082f
      SizeY = 0.914f
      SizeZ = 2.082f
    }
    {
      Name = "block-grass-overhang-large-slope-narrow"
      Path =
        "assets/kenney_platformer-kit/Models/block-grass-overhang-large-slope-narrow"
      SizeX = 1.082f
      SizeY = 0.914f
      SizeZ = 2.082f
    }
    {
      Name = "block-grass-overhang-large-slope-steep"
      Path =
        "assets/kenney_platformer-kit/Models/block-grass-overhang-large-slope-steep"
      SizeX = 2.082f
      SizeY = 1.367f
      SizeZ = 1.967f
    }
    {
      Name = "block-grass-overhang-large-slope-steep-narrow"
      Path =
        "assets/kenney_platformer-kit/Models/block-grass-overhang-large-slope-steep-narrow"
      SizeX = 1.082f
      SizeY = 1.367f
      SizeZ = 1.967f
    }
    {
      Name = "block-grass-overhang-large-tall"
      Path =
        "assets/kenney_platformer-kit/Models/block-grass-overhang-large-tall"
      SizeX = 2.082f
      SizeY = 2.0f
      SizeZ = 2.082f
    }
    {
      Name = "block-grass-overhang-long"
      Path = "assets/kenney_platformer-kit/Models/block-grass-overhang-long"
      SizeX = 2.082f
      SizeY = 1.0f
      SizeZ = 1.082f
    }
    {
      Name = "block-grass-overhang-low"
      Path = "assets/kenney_platformer-kit/Models/block-grass-overhang-low"
      SizeX = 1.082f
      SizeY = 0.5f
      SizeZ = 1.082f
    }
    {
      Name = "block-grass-overhang-low-hexagon"
      Path =
        "assets/kenney_platformer-kit/Models/block-grass-overhang-low-hexagon"
      SizeX = 1.1f
      SizeY = 0.5f
      SizeZ = 1.27f
    }
    {
      Name = "block-grass-overhang-low-large"
      Path =
        "assets/kenney_platformer-kit/Models/block-grass-overhang-low-large"
      SizeX = 2.082f
      SizeY = 0.5f
      SizeZ = 2.082f
    }
    {
      Name = "block-grass-overhang-low-long"
      Path = "assets/kenney_platformer-kit/Models/block-grass-overhang-low-long"
      SizeX = 2.082f
      SizeY = 0.5f
      SizeZ = 1.082f
    }
    {
      Name = "block-grass-overhang-low-narrow"
      Path =
        "assets/kenney_platformer-kit/Models/block-grass-overhang-low-narrow"
      SizeX = 0.782f
      SizeY = 0.5f
      SizeZ = 0.782f
    }
    {
      Name = "block-grass-overhang-narrow"
      Path = "assets/kenney_platformer-kit/Models/block-grass-overhang-narrow"
      SizeX = 0.782f
      SizeY = 1.0f
      SizeZ = 0.782f
    }
    {
      Name = "block-moving"
      Path = "assets/kenney_platformer-kit/Models/block-moving"
      SizeX = 1.0f
      SizeY = 0.3f
      SizeZ = 1.0f
    }
    {
      Name = "block-moving-blue"
      Path = "assets/kenney_platformer-kit/Models/block-moving-blue"
      SizeX = 1.0f
      SizeY = 0.5f
      SizeZ = 1.0f
    }
    {
      Name = "block-moving-large"
      Path = "assets/kenney_platformer-kit/Models/block-moving-large"
      SizeX = 1.0f
      SizeY = 0.5f
      SizeZ = 1.0f
    }
    {
      Name = "block-snow"
      Path = "assets/kenney_platformer-kit/Models/block-snow"
      SizeX = 1.082f
      SizeY = 1.0f
      SizeZ = 1.082f
    }
    {
      Name = "block-snow-corner"
      Path = "assets/kenney_platformer-kit/Models/block-snow-corner"
      SizeX = 1.054f
      SizeY = 1.0f
      SizeZ = 1.054f
    }
    {
      Name = "block-snow-corner-low"
      Path = "assets/kenney_platformer-kit/Models/block-snow-corner-low"
      SizeX = 1.054f
      SizeY = 0.5f
      SizeZ = 1.054f
    }
    {
      Name = "block-snow-corner-overhang"
      Path = "assets/kenney_platformer-kit/Models/block-snow-corner-overhang"
      SizeX = 1.054f
      SizeY = 1.0f
      SizeZ = 1.054f
    }
    {
      Name = "block-snow-corner-overhang-low"
      Path =
        "assets/kenney_platformer-kit/Models/block-snow-corner-overhang-low"
      SizeX = 1.054f
      SizeY = 0.5f
      SizeZ = 1.054f
    }
    {
      Name = "block-snow-curve"
      Path = "assets/kenney_platformer-kit/Models/block-snow-curve"
      SizeX = 2.0f
      SizeY = 1.0f
      SizeZ = 1.0f
    }
    {
      Name = "block-snow-curve-half"
      Path = "assets/kenney_platformer-kit/Models/block-snow-curve-half"
      SizeX = 1.0f
      SizeY = 1.0f
      SizeZ = 1.0f
    }
    {
      Name = "block-snow-curve-low"
      Path = "assets/kenney_platformer-kit/Models/block-snow-curve-low"
      SizeX = 2.0f
      SizeY = 0.5f
      SizeZ = 1.0f
    }
    {
      Name = "block-snow-edge"
      Path = "assets/kenney_platformer-kit/Models/block-snow-edge"
      SizeX = 1.082f
      SizeY = 1.0f
      SizeZ = 1.082f
    }
    {
      Name = "block-snow-hexagon"
      Path = "assets/kenney_platformer-kit/Models/block-snow-hexagon"
      SizeX = 1.1f
      SizeY = 1.0f
      SizeZ = 1.27f
    }
    {
      Name = "block-snow-large"
      Path = "assets/kenney_platformer-kit/Models/block-snow-large"
      SizeX = 2.082f
      SizeY = 1.0f
      SizeZ = 2.082f
    }
    {
      Name = "block-snow-large-slope"
      Path = "assets/kenney_platformer-kit/Models/block-snow-large-slope"
      SizeX = 2.082f
      SizeY = 0.759f
      SizeZ = 2.011f
    }
    {
      Name = "block-snow-large-slope-narrow"
      Path = "assets/kenney_platformer-kit/Models/block-snow-large-slope-narrow"
      SizeX = 1.082f
      SizeY = 0.759f
      SizeZ = 2.011f
    }
    {
      Name = "block-snow-large-slope-steep"
      Path = "assets/kenney_platformer-kit/Models/block-snow-large-slope-steep"
      SizeX = 2.082f
      SizeY = 1.217f
      SizeZ = 1.857f
    }
    {
      Name = "block-snow-large-slope-steep-narrow"
      Path =
        "assets/kenney_platformer-kit/Models/block-snow-large-slope-steep-narrow"
      SizeX = 1.082f
      SizeY = 1.217f
      SizeZ = 1.857f
    }
    {
      Name = "block-snow-large-tall"
      Path = "assets/kenney_platformer-kit/Models/block-snow-large-tall"
      SizeX = 2.082f
      SizeY = 2.0f
      SizeZ = 2.082f
    }
    {
      Name = "block-snow-long"
      Path = "assets/kenney_platformer-kit/Models/block-snow-long"
      SizeX = 2.082f
      SizeY = 1.0f
      SizeZ = 1.082f
    }
    {
      Name = "block-snow-low"
      Path = "assets/kenney_platformer-kit/Models/block-snow-low"
      SizeX = 1.082f
      SizeY = 0.5f
      SizeZ = 1.082f
    }
    {
      Name = "block-snow-low-hexagon"
      Path = "assets/kenney_platformer-kit/Models/block-snow-low-hexagon"
      SizeX = 1.1f
      SizeY = 0.5f
      SizeZ = 1.27f
    }
    {
      Name = "block-snow-low-large"
      Path = "assets/kenney_platformer-kit/Models/block-snow-low-large"
      SizeX = 2.082f
      SizeY = 0.5f
      SizeZ = 2.082f
    }
    {
      Name = "block-snow-low-long"
      Path = "assets/kenney_platformer-kit/Models/block-snow-low-long"
      SizeX = 2.082f
      SizeY = 0.5f
      SizeZ = 1.082f
    }
    {
      Name = "block-snow-low-narrow"
      Path = "assets/kenney_platformer-kit/Models/block-snow-low-narrow"
      SizeX = 0.782f
      SizeY = 0.5f
      SizeZ = 0.782f
    }
    {
      Name = "block-snow-narrow"
      Path = "assets/kenney_platformer-kit/Models/block-snow-narrow"
      SizeX = 0.782f
      SizeY = 1.0f
      SizeZ = 0.782f
    }
    {
      Name = "block-snow-overhang-corner"
      Path = "assets/kenney_platformer-kit/Models/block-snow-overhang-corner"
      SizeX = 1.082f
      SizeY = 1.0f
      SizeZ = 1.082f
    }
    {
      Name = "block-snow-overhang-edge"
      Path = "assets/kenney_platformer-kit/Models/block-snow-overhang-edge"
      SizeX = 1.082f
      SizeY = 1.0f
      SizeZ = 1.082f
    }
    {
      Name = "block-snow-overhang-hexagon"
      Path = "assets/kenney_platformer-kit/Models/block-snow-overhang-hexagon"
      SizeX = 1.1f
      SizeY = 1.0f
      SizeZ = 1.27f
    }
    {
      Name = "block-snow-overhang-large"
      Path = "assets/kenney_platformer-kit/Models/block-snow-overhang-large"
      SizeX = 2.082f
      SizeY = 1.0f
      SizeZ = 2.082f
    }
    {
      Name = "block-snow-overhang-large-slope"
      Path =
        "assets/kenney_platformer-kit/Models/block-snow-overhang-large-slope"
      SizeX = 2.082f
      SizeY = 0.914f
      SizeZ = 2.082f
    }
    {
      Name = "block-snow-overhang-large-slope-narrow"
      Path =
        "assets/kenney_platformer-kit/Models/block-snow-overhang-large-slope-narrow"
      SizeX = 1.082f
      SizeY = 0.775f
      SizeZ = 2.011f
    }
    {
      Name = "block-snow-overhang-large-slope-steep"
      Path =
        "assets/kenney_platformer-kit/Models/block-snow-overhang-large-slope-steep"
      SizeX = 2.082f
      SizeY = 1.367f
      SizeZ = 1.967f
    }
    {
      Name = "block-snow-overhang-large-slope-steep-narrow"
      Path =
        "assets/kenney_platformer-kit/Models/block-snow-overhang-large-slope-steep-narrow"
      SizeX = 1.082f
      SizeY = 1.217f
      SizeZ = 1.857f
    }
    {
      Name = "block-snow-overhang-large-tall"
      Path =
        "assets/kenney_platformer-kit/Models/block-snow-overhang-large-tall"
      SizeX = 2.082f
      SizeY = 2.0f
      SizeZ = 2.082f
    }
    {
      Name = "block-snow-overhang-long"
      Path = "assets/kenney_platformer-kit/Models/block-snow-overhang-long"
      SizeX = 2.082f
      SizeY = 1.0f
      SizeZ = 1.082f
    }
    {
      Name = "block-snow-overhang-low"
      Path = "assets/kenney_platformer-kit/Models/block-snow-overhang-low"
      SizeX = 1.082f
      SizeY = 0.5f
      SizeZ = 1.082f
    }
    {
      Name = "block-snow-overhang-low-hexagon"
      Path =
        "assets/kenney_platformer-kit/Models/block-snow-overhang-low-hexagon"
      SizeX = 1.1f
      SizeY = 0.5f
      SizeZ = 1.27f
    }
    {
      Name = "block-snow-overhang-low-large"
      Path = "assets/kenney_platformer-kit/Models/block-snow-overhang-low-large"
      SizeX = 2.082f
      SizeY = 0.5f
      SizeZ = 2.082f
    }
    {
      Name = "block-snow-overhang-low-long"
      Path = "assets/kenney_platformer-kit/Models/block-snow-overhang-low-long"
      SizeX = 2.082f
      SizeY = 0.5f
      SizeZ = 1.082f
    }
    {
      Name = "block-snow-overhang-low-narrow"
      Path =
        "assets/kenney_platformer-kit/Models/block-snow-overhang-low-narrow"
      SizeX = 0.782f
      SizeY = 0.5f
      SizeZ = 0.782f
    }
    {
      Name = "block-snow-overhang-narrow"
      Path = "assets/kenney_platformer-kit/Models/block-snow-overhang-narrow"
      SizeX = 0.782f
      SizeY = 1.0f
      SizeZ = 0.782f
    }
    {
      Name = "bomb"
      Path = "assets/kenney_platformer-kit/Models/bomb"
      SizeX = 0.493f
      SizeY = 0.542f
      SizeZ = 0.493f
    }
    {
      Name = "brick"
      Path = "assets/kenney_platformer-kit/Models/brick"
      SizeX = 0.5f
      SizeY = 0.5f
      SizeZ = 0.5f
    }
    {
      Name = "button-round"
      Path = "assets/kenney_platformer-kit/Models/button-round"
      SizeX = 0.58f
      SizeY = 0.185f
      SizeZ = 0.502f
    }
    {
      Name = "button-square"
      Path = "assets/kenney_platformer-kit/Models/button-square"
      SizeX = 0.6f
      SizeY = 0.2f
      SizeZ = 0.6f
    }
    {
      Name = "character-oobi"
      Path = "assets/kenney_platformer-kit/Models/character-oobi"
      SizeX = 0.868f
      SizeY = 0.907f
      SizeZ = 0.603f
    }
    {
      Name = "character-oodi"
      Path = "assets/kenney_platformer-kit/Models/character-oodi"
      SizeX = 0.868f
      SizeY = 0.907f
      SizeZ = 0.61f
    }
    {
      Name = "character-ooli"
      Path = "assets/kenney_platformer-kit/Models/character-ooli"
      SizeX = 0.868f
      SizeY = 0.907f
      SizeZ = 0.603f
    }
    {
      Name = "character-oopi"
      Path = "assets/kenney_platformer-kit/Models/character-oopi"
      SizeX = 0.868f
      SizeY = 0.907f
      SizeZ = 0.603f
    }
    {
      Name = "character-oozi"
      Path = "assets/kenney_platformer-kit/Models/character-oozi"
      SizeX = 0.868f
      SizeY = 0.907f
      SizeZ = 0.609f
    }
    {
      Name = "chest"
      Path = "assets/kenney_platformer-kit/Models/chest"
      SizeX = 0.5f
      SizeY = 0.3f
      SizeZ = 0.7f
    }
    {
      Name = "coin-bronze"
      Path = "assets/kenney_platformer-kit/Models/coin-bronze"
      SizeX = 0.4f
      SizeY = 0.4f
      SizeZ = 0.175f
    }
    {
      Name = "coin-gold"
      Path = "assets/kenney_platformer-kit/Models/coin-gold"
      SizeX = 0.4f
      SizeY = 0.4f
      SizeZ = 0.175f
    }
    {
      Name = "coin-silver"
      Path = "assets/kenney_platformer-kit/Models/coin-silver"
      SizeX = 0.4f
      SizeY = 0.4f
      SizeZ = 0.175f
    }
    {
      Name = "conveyor-belt"
      Path = "assets/kenney_platformer-kit/Models/conveyor-belt"
      SizeX = 1.0f
      SizeY = 0.3f
      SizeZ = 1.0f
    }
    {
      Name = "crate"
      Path = "assets/kenney_platformer-kit/Models/crate"
      SizeX = 0.5f
      SizeY = 0.5f
      SizeZ = 0.5f
    }
    {
      Name = "crate-item"
      Path = "assets/kenney_platformer-kit/Models/crate-item"
      SizeX = 0.5f
      SizeY = 0.5f
      SizeZ = 0.5f
    }
    {
      Name = "crate-item-strong"
      Path = "assets/kenney_platformer-kit/Models/crate-item-strong"
      SizeX = 0.6f
      SizeY = 0.6f
      SizeZ = 0.6f
    }
    {
      Name = "crate-strong"
      Path = "assets/kenney_platformer-kit/Models/crate-strong"
      SizeX = 0.6f
      SizeY = 0.6f
      SizeZ = 0.6f
    }
    {
      Name = "door-large-open"
      Path = "assets/kenney_platformer-kit/Models/door-large-open"
      SizeX = 1.0f
      SizeY = 1.0f
      SizeZ = 0.3f
    }
    {
      Name = "door-open"
      Path = "assets/kenney_platformer-kit/Models/door-open"
      SizeX = 0.6f
      SizeY = 1.0f
      SizeZ = 0.2f
    }
    {
      Name = "door-rotate"
      Path = "assets/kenney_platformer-kit/Models/door-rotate"
      SizeX = 0.724f
      SizeY = 1.0f
      SizeZ = 0.2f
    }
    {
      Name = "door-rotate-large"
      Path = "assets/kenney_platformer-kit/Models/door-rotate-large"
      SizeX = 1.124f
      SizeY = 1.0f
      SizeZ = 0.3f
    }
    {
      Name = "fence-broken"
      Path = "assets/kenney_platformer-kit/Models/fence-broken"
      SizeX = 1.026f
      SizeY = 0.4f
      SizeZ = 0.14f
    }
    {
      Name = "fence-corner"
      Path = "assets/kenney_platformer-kit/Models/fence-corner"
      SizeX = 0.99f
      SizeY = 0.4f
      SizeZ = 0.99f
    }
    {
      Name = "fence-corner-curved"
      Path = "assets/kenney_platformer-kit/Models/fence-corner-curved"
      SizeX = 0.99f
      SizeY = 0.4f
      SizeZ = 0.99f
    }
    {
      Name = "fence-low-broken"
      Path = "assets/kenney_platformer-kit/Models/fence-low-broken"
      SizeX = 1.0f
      SizeY = 0.3f
      SizeZ = 0.2f
    }
    {
      Name = "fence-low-corner"
      Path = "assets/kenney_platformer-kit/Models/fence-low-corner"
      SizeX = 1.0f
      SizeY = 0.3f
      SizeZ = 1.0f
    }
    {
      Name = "fence-low-corner-curved"
      Path = "assets/kenney_platformer-kit/Models/fence-low-corner-curved"
      SizeX = 1.0f
      SizeY = 0.3f
      SizeZ = 1.0f
    }
    {
      Name = "fence-low-straight"
      Path = "assets/kenney_platformer-kit/Models/fence-low-straight"
      SizeX = 1.0f
      SizeY = 0.3f
      SizeZ = 0.2f
    }
    {
      Name = "fence-rope"
      Path = "assets/kenney_platformer-kit/Models/fence-rope"
      SizeX = 0.95f
      SizeY = 0.3f
      SizeZ = 0.21f
    }
    {
      Name = "fence-straight"
      Path = "assets/kenney_platformer-kit/Models/fence-straight"
      SizeX = 1.0f
      SizeY = 0.4f
      SizeZ = 0.14f
    }
    {
      Name = "flag"
      Path = "assets/kenney_platformer-kit/Models/flag"
      SizeX = 0.423f
      SizeY = 0.9f
      SizeZ = 0.112f
    }
    {
      Name = "flowers"
      Path = "assets/kenney_platformer-kit/Models/flowers"
      SizeX = 0.777f
      SizeY = 0.137f
      SizeZ = 0.786f
    }
    {
      Name = "flowers-tall"
      Path = "assets/kenney_platformer-kit/Models/flowers-tall"
      SizeX = 0.546f
      SizeY = 0.462f
      SizeZ = 0.618f
    }
    {
      Name = "grass"
      Path = "assets/kenney_platformer-kit/Models/grass"
      SizeX = 0.519f
      SizeY = 0.314f
      SizeZ = 0.544f
    }
    {
      Name = "heart"
      Path = "assets/kenney_platformer-kit/Models/heart"
      SizeX = 0.412f
      SizeY = 0.384f
      SizeZ = 0.119f
    }
    {
      Name = "hedge"
      Path = "assets/kenney_platformer-kit/Models/hedge"
      SizeX = 1.0f
      SizeY = 0.4f
      SizeZ = 0.3f
    }
    {
      Name = "hedge-corner"
      Path = "assets/kenney_platformer-kit/Models/hedge-corner"
      SizeX = 1.0f
      SizeY = 0.4f
      SizeZ = 1.0f
    }
    {
      Name = "jewel"
      Path = "assets/kenney_platformer-kit/Models/jewel"
      SizeX = 0.333f
      SizeY = 0.37f
      SizeZ = 0.288f
    }
    {
      Name = "key"
      Path = "assets/kenney_platformer-kit/Models/key"
      SizeX = 0.382f
      SizeY = 0.217f
      SizeZ = 0.068f
    }
    {
      Name = "ladder"
      Path = "assets/kenney_platformer-kit/Models/ladder"
      SizeX = 0.5f
      SizeY = 1.0f
      SizeZ = 0.1f
    }
    {
      Name = "ladder-broken"
      Path = "assets/kenney_platformer-kit/Models/ladder-broken"
      SizeX = 0.5f
      SizeY = 1.0f
      SizeZ = 0.1f
    }
    {
      Name = "ladder-long"
      Path = "assets/kenney_platformer-kit/Models/ladder-long"
      SizeX = 0.5f
      SizeY = 2.0f
      SizeZ = 0.1f
    }
    {
      Name = "lever"
      Path = "assets/kenney_platformer-kit/Models/lever"
      SizeX = 0.6f
      SizeY = 0.542f
      SizeZ = 0.45f
    }
    {
      Name = "lock"
      Path = "assets/kenney_platformer-kit/Models/lock"
      SizeX = 0.343f
      SizeY = 0.401f
      SizeZ = 0.185f
    }
    {
      Name = "mushrooms"
      Path = "assets/kenney_platformer-kit/Models/mushrooms"
      SizeX = 0.522f
      SizeY = 0.289f
      SizeZ = 0.512f
    }
    {
      Name = "pipe"
      Path = "assets/kenney_platformer-kit/Models/pipe"
      SizeX = 1.0f
      SizeY = 0.564f
      SizeZ = 1.0f
    }
    {
      Name = "plant"
      Path = "assets/kenney_platformer-kit/Models/plant"
      SizeX = 0.511f
      SizeY = 0.172f
      SizeZ = 0.443f
    }
    {
      Name = "platform"
      Path = "assets/kenney_platformer-kit/Models/platform"
      SizeX = 1.0f
      SizeY = 0.195f
      SizeZ = 1.0f
    }
    {
      Name = "platform-fortified"
      Path = "assets/kenney_platformer-kit/Models/platform-fortified"
      SizeX = 1.0f
      SizeY = 0.205f
      SizeZ = 1.0f
    }
    {
      Name = "platform-overhang"
      Path = "assets/kenney_platformer-kit/Models/platform-overhang"
      SizeX = 1.0f
      SizeY = 0.432f
      SizeZ = 0.458f
    }
    {
      Name = "platform-ramp"
      Path = "assets/kenney_platformer-kit/Models/platform-ramp"
      SizeX = 1.0f
      SizeY = 0.57f
      SizeZ = 1.027f
    }
    {
      Name = "poles"
      Path = "assets/kenney_platformer-kit/Models/poles"
      SizeX = 1.1f
      SizeY = 1.0f
      SizeZ = 0.35f
    }
    {
      Name = "rocks"
      Path = "assets/kenney_platformer-kit/Models/rocks"
      SizeX = 0.653f
      SizeY = 0.4f
      SizeZ = 0.662f
    }
    {
      Name = "saw"
      Path = "assets/kenney_platformer-kit/Models/saw"
      SizeX = 0.794f
      SizeY = 0.794f
      SizeZ = 0.303f
    }
    {
      Name = "sign"
      Path = "assets/kenney_platformer-kit/Models/sign"
      SizeX = 0.483f
      SizeY = 0.6f
      SizeZ = 0.131f
    }
    {
      Name = "spike-block"
      Path = "assets/kenney_platformer-kit/Models/spike-block"
      SizeX = 0.9f
      SizeY = 0.9f
      SizeZ = 0.9f
    }
    {
      Name = "spike-block-wide"
      Path = "assets/kenney_platformer-kit/Models/spike-block-wide"
      SizeX = 2.4f
      SizeY = 0.9f
      SizeZ = 0.9f
    }
    {
      Name = "spring"
      Path = "assets/kenney_platformer-kit/Models/spring"
      SizeX = 0.75f
      SizeY = 0.332f
      SizeZ = 0.75f
    }
    {
      Name = "star"
      Path = "assets/kenney_platformer-kit/Models/star"
      SizeX = 0.365f
      SizeY = 0.363f
      SizeZ = 0.239f
    }
    {
      Name = "stones"
      Path = "assets/kenney_platformer-kit/Models/stones"
      SizeX = 0.71f
      SizeY = 0.05f
      SizeZ = 0.79f
    }
    {
      Name = "trap-spikes"
      Path = "assets/kenney_platformer-kit/Models/trap-spikes"
      SizeX = 0.639f
      SizeY = 0.255f
      SizeZ = 0.638f
    }
    {
      Name = "trap-spikes-large"
      Path = "assets/kenney_platformer-kit/Models/trap-spikes-large"
      SizeX = 0.765f
      SizeY = 0.255f
      SizeZ = 0.765f
    }
    {
      Name = "tree"
      Path = "assets/kenney_platformer-kit/Models/tree"
      SizeX = 1.089f
      SizeY = 1.931f
      SizeZ = 1.109f
    }
    {
      Name = "tree-pine"
      Path = "assets/kenney_platformer-kit/Models/tree-pine"
      SizeX = 0.948f
      SizeY = 1.997f
      SizeZ = 0.948f
    }
    {
      Name = "tree-pine-small"
      Path = "assets/kenney_platformer-kit/Models/tree-pine-small"
      SizeX = 0.664f
      SizeY = 1.398f
      SizeZ = 0.664f
    }
    {
      Name = "tree-pine-snow"
      Path = "assets/kenney_platformer-kit/Models/tree-pine-snow"
      SizeX = 0.948f
      SizeY = 1.997f
      SizeZ = 0.948f
    }
    {
      Name = "tree-pine-snow-small"
      Path = "assets/kenney_platformer-kit/Models/tree-pine-snow-small"
      SizeX = 0.664f
      SizeY = 1.398f
      SizeZ = 0.664f
    }
    {
      Name = "tree-snow"
      Path = "assets/kenney_platformer-kit/Models/tree-snow"
      SizeX = 1.089f
      SizeY = 1.931f
      SizeZ = 1.109f
    }
  |]

  /// O(1) name index over the baked dataset (built once at module init).
  let byName: FrozenDictionary<string, ModelInfo> =
    all
    |> Seq.map(fun t -> KeyValuePair(t.Name, t))
    |> FrozenDictionary.ToFrozenDictionary

  /// Safe name lookup for data-driven code.
  let tryByName(name: string) : ModelInfo voption =
    match byName.TryGetValue name with
    | true, info -> ValueSome info
    | false, _ -> ValueNone
