// ─────────────────────────────────────────────────────────────
// GENERATED by tools/gen-tiles.fsx — DO NOT EDIT BY HAND.
// Regenerate with:  dotnet fsi tools/gen-tiles.fsx --xml assets/kenney_tower-defense-top-down/towerDefense_tilesheet.xml --out LiveMap/Catalog/Tiles.fs --namespace LiveMap.Catalog --module Tiles --sheet-path kenney_tower-defense-top-down/towerDefense_tilesheet.png --tile-size --curation LiveMap/Catalog/Tiles.curation
// Sources: assets/kenney_tower-defense-top-down/towerDefense_tilesheet.xml
// ─────────────────────────────────────────────────────────────
namespace LiveMap.Catalog

open System.Collections.Frozen
open System.Collections.Generic

module Tiles =

  [<Literal>]
  let SheetPath = "kenney_tower-defense-top-down/towerDefense_tilesheet.png"

  [<Literal>]
  let TileSize = 64

  /// All 299 atlas tiles (name, position, size) baked at compile time.
  /// Canonical store: ordered and iterable. The name index is built from it.
  let all: TileInfo[] = [|
    {
      Name = "grass_patch_on_dirt_top_left"
      X = 0
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_top"
      X = 64
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_top_right"
      X = 128
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_grass_top_left"
      X = 192
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_grass_top_right"
      X = 256
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_top_left"
      X = 320
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_top"
      X = 384
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_top_right"
      X = 448
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_sand_top_left"
      X = 512
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_sand_top_right"
      X = 576
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_top_left"
      X = 640
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_top"
      X = 704
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_top_right"
      X = 768
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_stone_top_left"
      X = 832
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_stone_top_right"
      X = 896
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "button_white"
      X = 960
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "button_white_wrench"
      X = 1024
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "button_white_close"
      X = 1088
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "button_white_target"
      X = 1152
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "effect_impact_ring"
      X = 1216
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "effect_impact_debris"
      X = 1280
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "effect_impact_burst"
      X = 1344
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "crosshair"
      X = 1408
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_left"
      X = 0
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_center"
      X = 64
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_right"
      X = 128
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_grass_bottom_left"
      X = 192
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_grass_bottom_right"
      X = 256
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_left"
      X = 320
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_center"
      X = 384
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_right"
      X = 448
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_sand_bottom_left"
      X = 512
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_sand_bottom_right"
      X = 576
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_left"
      X = 640
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_center"
      X = 704
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_right"
      X = 768
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_stone_bottom_left"
      X = 832
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_stone_bottom_right"
      X = 896
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green"
      X = 960
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green_wrench"
      X = 1024
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green_close"
      X = 1088
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green_target"
      X = 1152
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green_alt"
      X = 1216
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green_wrench_alt"
      X = 1280
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green_close_alt"
      X = 1344
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green_target_alt"
      X = 1408
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_bottom_left"
      X = 0
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_bottom"
      X = 64
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_bottom_right"
      X = 128
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "grass_dot_on_dirt"
      X = 192
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_full_a"
      X = 256
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_bottom_left"
      X = 320
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_bottom"
      X = 384
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_bottom_right"
      X = 448
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "sand_dot_on_dirt"
      X = 512
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_full_b"
      X = 576
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_bottom_left"
      X = 640
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_bottom"
      X = 704
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_bottom_right"
      X = 768
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "stone_dot_on_dirt"
      X = 832
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_full_c"
      X = 896
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown"
      X = 960
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown_wrench"
      X = 1024
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown_close"
      X = 1088
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown_target"
      X = 1152
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown_alt"
      X = 1216
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown_wrench_alt"
      X = 1280
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown_close_alt"
      X = 1344
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown_target_alt"
      X = 1408
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_top_left"
      X = 0
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_top"
      X = 64
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_top_right"
      X = 128
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_dirt_top_left"
      X = 192
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_dirt_top_right"
      X = 256
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_top_left"
      X = 320
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_top"
      X = 384
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_top_right"
      X = 448
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_sand_top_left"
      X = 512
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_sand_top_right"
      X = 576
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_top_left"
      X = 640
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_top"
      X = 704
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_top_right"
      X = 768
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_stone_top_left"
      X = 832
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_stone_top_right"
      X = 896
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel"
      X = 960
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel_wrench"
      X = 1024
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel_close"
      X = 1088
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel_target"
      X = 1152
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel_alt"
      X = 1216
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel_wrench_alt"
      X = 1280
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel_close_alt"
      X = 1344
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel_target_alt"
      X = 1408
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_left"
      X = 0
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_center"
      X = 64
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_right"
      X = 128
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_dirt_bottom_left"
      X = 192
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_dirt_bottom_right"
      X = 256
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_left"
      X = 320
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_center"
      X = 384
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_right"
      X = 448
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_sand_bottom_left"
      X = 512
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_sand_bottom_right"
      X = 576
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_left"
      X = 640
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_center"
      X = 704
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_right"
      X = 768
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_stone_bottom_left"
      X = 832
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_stone_bottom_right"
      X = 896
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige"
      X = 960
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige_wrench"
      X = 1024
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige_close"
      X = 1088
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige_target"
      X = 1152
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige_alt"
      X = 1216
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige_wrench_alt"
      X = 1280
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige_close_alt"
      X = 1344
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige_target_alt"
      X = 1408
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_bottom_left"
      X = 0
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_bottom"
      X = 64
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_bottom_right"
      X = 128
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_dot_on_grass"
      X = 192
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "grass_full_a"
      X = 256
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_bottom_left"
      X = 320
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_bottom"
      X = 384
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_bottom_right"
      X = 448
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "sand_dot_on_grass"
      X = 512
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "grass_full_b"
      X = 576
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_bottom_left"
      X = 640
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_bottom"
      X = 704
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_bottom_right"
      X = 768
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "stone_dot_on_grass"
      X = 832
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "grass_full_c"
      X = 896
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "tree_large"
      X = 960
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "bush_small"
      X = 1024
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "plant_sprig"
      X = 1088
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "tree_round"
      X = 1152
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "tree_pine"
      X = 1216
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "rock_small"
      X = 1280
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "rock_large"
      X = 1344
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "rock_medium"
      X = 1408
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_top_left"
      X = 0
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_top"
      X = 64
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_top_right"
      X = 128
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_grass_top_left"
      X = 192
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_grass_top_right"
      X = 256
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_top_left"
      X = 320
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_top"
      X = 384
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_top_right"
      X = 448
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_dirt_top_left"
      X = 512
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_dirt_top_right"
      X = 576
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_top_left"
      X = 640
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_top"
      X = 704
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_top_right"
      X = 768
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_stone_top_left"
      X = 832
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_stone_top_right"
      X = 896
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_up_grass"
      X = 960
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_up_dirt"
      X = 1024
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_up_stone"
      X = 1088
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_up_sand"
      X = 1152
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "grass_full_textured"
      X = 1216
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_full_textured"
      X = 1280
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "stone_full_textured"
      X = 1344
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "sand_full_textured"
      X = 1408
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_left"
      X = 0
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_center"
      X = 64
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_right"
      X = 128
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_grass_bottom_left"
      X = 192
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_grass_bottom_right"
      X = 256
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_left"
      X = 320
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_center"
      X = 384
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_right"
      X = 448
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_dirt_bottom_left"
      X = 512
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_dirt_bottom_right"
      X = 576
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_left"
      X = 640
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_center"
      X = 704
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_right"
      X = 768
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_stone_bottom_left"
      X = 832
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_stone_bottom_right"
      X = 896
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "path_vertical_grass"
      X = 960
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "path_vertical_dirt"
      X = 1024
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "path_vertical_stone"
      X = 1088
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "path_vertical_sand"
      X = 1152
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "crate_metal_square"
      X = 1216
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "crate_metal_octagon"
      X = 1280
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "crate_metal_beveled"
      X = 1344
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "crate_metal_diamond"
      X = 1408
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_bottom_left"
      X = 0
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_bottom"
      X = 64
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_bottom_right"
      X = 128
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "grass_dot_on_sand"
      X = 192
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "sand_full_a"
      X = 256
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_bottom_left"
      X = 320
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_bottom"
      X = 384
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_bottom_right"
      X = 448
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_dot_on_sand"
      X = 512
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "sand_full_b"
      X = 576
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_bottom_left"
      X = 640
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_bottom"
      X = 704
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_bottom_right"
      X = 768
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "stone_dot_on_sand"
      X = 832
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "sand_full_c"
      X = 896
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_left_grass"
      X = 960
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_left_dirt"
      X = 1024
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_left_stone"
      X = 1088
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_left_sand"
      X = 1152
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "turret_mount_empty"
      X = 1216
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "turret_missiles_dual"
      X = 1280
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "rocket_pod_dual"
      X = 1344
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "rocket_pod_single"
      X = 1408
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_top_left"
      X = 0
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_top"
      X = 64
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_top_right"
      X = 128
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_grass_top_left"
      X = 192
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_grass_top_right"
      X = 256
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_top_left"
      X = 320
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_top"
      X = 384
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_top_right"
      X = 448
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_dirt_top_left"
      X = 512
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_dirt_top_right"
      X = 576
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_top_left"
      X = 640
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_top"
      X = 704
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_top_right"
      X = 768
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_sand_top_left"
      X = 832
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_sand_top_right"
      X = 896
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "path_horizontal_grass"
      X = 960
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "path_horizontal_dirt"
      X = 1024
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "path_horizontal_stone"
      X = 1088
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "path_horizontal_sand"
      X = 1152
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "turret_base_a"
      X = 1216
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "turret_base_b"
      X = 1280
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "container_large"
      X = 1344
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "container_small"
      X = 1408
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_left"
      X = 0
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_center"
      X = 64
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_right"
      X = 128
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_grass_bottom_left"
      X = 192
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_grass_bottom_right"
      X = 256
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_left"
      X = 320
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_center"
      X = 384
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_right"
      X = 448
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_dirt_bottom_left"
      X = 512
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_dirt_bottom_right"
      X = 576
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_left"
      X = 640
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_center"
      X = 704
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_right"
      X = 768
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_sand_bottom_left"
      X = 832
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_sand_bottom_right"
      X = 896
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "soldier_green"
      X = 960
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "soldier_slate"
      X = 1024
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "soldier_brown"
      X = 1088
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "soldier_gray"
      X = 1152
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "turret_green"
      X = 1216
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "turret_red_dual"
      X = 1280
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "rocket_small"
      X = 1344
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "rocket_large"
      X = 1408
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_bottom_left"
      X = 0
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_bottom"
      X = 64
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_bottom_right"
      X = 128
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "grass_dot_on_stone"
      X = 192
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "stone_full_a"
      X = 256
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_bottom_left"
      X = 320
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_bottom"
      X = 384
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_bottom_right"
      X = 448
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_dot_on_stone"
      X = 512
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "stone_full_b"
      X = 576
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_bottom_left"
      X = 640
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_bottom"
      X = 704
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_bottom_right"
      X = 768
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "sand_dot_on_stone"
      X = 832
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "stone_full_c"
      X = 896
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "tank_hull_green"
      X = 961
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "tank_hull_beige"
      X = 1025
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "plane_green"
      X = 1088
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "plane_gray"
      X = 1152
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "coin_gold"
      X = 1216
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "coin_gold_rimmed"
      X = 1280
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "coin_copper"
      X = 1344
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "coin_silver"
      X = 1408
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "digit_0"
      X = 0
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_1"
      X = 64
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_2"
      X = 128
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_3"
      X = 192
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_4"
      X = 256
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_5"
      X = 320
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_6"
      X = 384
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_7"
      X = 448
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_8"
      X = 512
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_9"
      X = 576
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "symbol_percent"
      X = 640
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "symbol_dollar"
      X = 704
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "symbol_colon"
      X = 768
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "symbol_plus"
      X = 832
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "symbol_period"
      X = 896
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "tank_turret_green"
      X = 960
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "tank_turret_beige"
      X = 1024
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "plane_ghost_a"
      X = 1088
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "plane_ghost_b"
      X = 1152
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "flame_small"
      X = 1216
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "flame_large"
      X = 1280
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "flame_thin"
      X = 1344
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "flame_spread"
      X = 1408
      Y = 768
      Width = 64
      Height = 64
    }
  |]

  /// O(1) name index over the baked dataset (built once at module init).
  let byName: FrozenDictionary<string, TileInfo> =
    all
    |> Seq.map(fun t -> KeyValuePair(t.Name, t))
    |> FrozenDictionary.ToFrozenDictionary

  /// Safe name lookup for data-driven code (map documents, procedural gen).
  let tryByName(name: string) : TileInfo voption =
    match byName.TryGetValue name with
    | true, info -> ValueSome info
    | false, _ -> ValueNone

  // ── Semantically named tiles (curated in the generator's input) ──
  /// grass_full_a — atlas position (256, 320), 64x64.
  let grass = byName["grass_full_a"]
  /// grass_full_b — atlas position (576, 320), 64x64.
  let grassB = byName["grass_full_b"]
  /// grass_full_c — atlas position (896, 320), 64x64.
  let grassC = byName["grass_full_c"]
  /// dirt_full_a — atlas position (256, 128), 64x64.
  let dirt = byName["dirt_full_a"]
  /// dirt_full_b — atlas position (576, 128), 64x64.
  let dirtB = byName["dirt_full_b"]
  /// dirt_full_c — atlas position (896, 128), 64x64.
  let dirtC = byName["dirt_full_c"]
  /// sand_full_a — atlas position (256, 512), 64x64.
  let sand = byName["sand_full_a"]
  /// sand_full_b — atlas position (576, 512), 64x64.
  let sandB = byName["sand_full_b"]
  /// sand_full_c — atlas position (896, 512), 64x64.
  let sandC = byName["sand_full_c"]
  /// stone_full_a — atlas position (256, 704), 64x64.
  let stone = byName["stone_full_a"]
  /// stone_full_b — atlas position (576, 704), 64x64.
  let stoneB = byName["stone_full_b"]
  /// stone_full_c — atlas position (896, 704), 64x64.
  let stoneC = byName["stone_full_c"]
  /// path_vertical_dirt — atlas position (1024, 448), 64x64.
  let pathVerticalDirt = byName["path_vertical_dirt"]
  /// path_horizontal_dirt — atlas position (1024, 576), 64x64.
  let pathHorizontalDirt = byName["path_horizontal_dirt"]
  /// path_end_up_dirt — atlas position (1024, 384), 64x64.
  let pathEndUpDirt = byName["path_end_up_dirt"]
  /// path_end_left_dirt — atlas position (1024, 512), 64x64.
  let pathEndLeftDirt = byName["path_end_left_dirt"]
  /// path_vertical_stone — atlas position (1088, 448), 64x64.
  let pathVerticalStone = byName["path_vertical_stone"]
  /// path_horizontal_stone — atlas position (1088, 576), 64x64.
  let pathHorizontalStone = byName["path_horizontal_stone"]
  /// path_end_up_stone — atlas position (1088, 384), 64x64.
  let pathEndUpStone = byName["path_end_up_stone"]
  /// path_end_left_stone — atlas position (1088, 512), 64x64.
  let pathEndLeftStone = byName["path_end_left_stone"]
  /// bush_small — atlas position (1024, 320), 64x64.
  let bush = byName["bush_small"]
  /// rock_small — atlas position (1280, 320), 64x64.
  let rockSmall = byName["rock_small"]
  /// rock_medium — atlas position (1408, 320), 64x64.
  let rockMedium = byName["rock_medium"]
  /// rock_large — atlas position (1344, 320), 64x64.
  let rockLarge = byName["rock_large"]
  /// tree_round — atlas position (1152, 320), 64x64.
  let treeRound = byName["tree_round"]
  /// tree_pine — atlas position (1216, 320), 64x64.
  let treePine = byName["tree_pine"]
  /// crate_metal_square — atlas position (1216, 448), 64x64.
  let crate = byName["crate_metal_square"]
  /// crate_metal_beveled — atlas position (1344, 448), 64x64.
  let crateBeveled = byName["crate_metal_beveled"]
  /// container_small — atlas position (1408, 576), 64x64.
  let container = byName["container_small"]
  /// container_large — atlas position (1344, 576), 64x64.
  let containerLarge = byName["container_large"]
  /// coin_gold — atlas position (1216, 704), 64x64.
  let coin = byName["coin_gold"]
  /// turret_mount_empty — atlas position (1216, 512), 64x64.
  let turretMount = byName["turret_mount_empty"]
  /// turret_base_a — atlas position (1216, 576), 64x64.
  let turretBase = byName["turret_base_a"]
  /// grass_dot_on_dirt — atlas position (192, 128), 64x64.
  let grassDotOnDirt = byName["grass_dot_on_dirt"]
  /// sand_dot_on_dirt — atlas position (512, 128), 64x64.
  let sandDotOnDirt = byName["sand_dot_on_dirt"]
  /// stone_dot_on_dirt — atlas position (832, 128), 64x64.
  let stoneDotOnDirt = byName["stone_dot_on_dirt"]
  /// dirt_dot_on_grass — atlas position (192, 320), 64x64.
  let dirtDotOnGrass = byName["dirt_dot_on_grass"]
  /// sand_dot_on_grass — atlas position (512, 320), 64x64.
  let sandDotOnGrass = byName["sand_dot_on_grass"]
  /// stone_dot_on_grass — atlas position (832, 320), 64x64.
  let stoneDotOnGrass = byName["stone_dot_on_grass"]
  /// grass_dot_on_sand — atlas position (192, 512), 64x64.
  let grassDotOnSand = byName["grass_dot_on_sand"]
  /// dirt_dot_on_sand — atlas position (512, 512), 64x64.
  let dirtDotOnSand = byName["dirt_dot_on_sand"]
  /// stone_dot_on_sand — atlas position (832, 512), 64x64.
  let stoneDotOnSand = byName["stone_dot_on_sand"]
  /// grass_dot_on_stone — atlas position (192, 704), 64x64.
  let grassDotOnStone = byName["grass_dot_on_stone"]
  /// dirt_dot_on_stone — atlas position (512, 704), 64x64.
  let dirtDotOnStone = byName["dirt_dot_on_stone"]
  /// sand_dot_on_stone — atlas position (832, 704), 64x64.
  let sandDotOnStone = byName["sand_dot_on_stone"]
  /// grass_patch_on_dirt_center — atlas position (64, 64), 64x64.
  let grassPatchOnDirt = byName["grass_patch_on_dirt_center"]
  /// sand_patch_on_dirt_center — atlas position (384, 64), 64x64.
  let sandPatchOnDirt = byName["sand_patch_on_dirt_center"]
  /// stone_patch_on_dirt_center — atlas position (704, 64), 64x64.
  let stonePatchOnDirt = byName["stone_patch_on_dirt_center"]
  /// dirt_patch_on_grass_center — atlas position (64, 256), 64x64.
  let dirtPatchOnGrass = byName["dirt_patch_on_grass_center"]
  /// sand_patch_on_grass_center — atlas position (384, 256), 64x64.
  let sandPatchOnGrass = byName["sand_patch_on_grass_center"]
  /// stone_patch_on_grass_center — atlas position (704, 256), 64x64.
  let stonePatchOnGrass = byName["stone_patch_on_grass_center"]
  /// grass_patch_on_sand_center — atlas position (64, 448), 64x64.
  let grassPatchOnSand = byName["grass_patch_on_sand_center"]
  /// dirt_patch_on_sand_center — atlas position (384, 448), 64x64.
  let dirtPatchOnSand = byName["dirt_patch_on_sand_center"]
  /// stone_patch_on_sand_center — atlas position (704, 448), 64x64.
  let stonePatchOnSand = byName["stone_patch_on_sand_center"]
  /// grass_patch_on_stone_center — atlas position (64, 640), 64x64.
  let grassPatchOnStone = byName["grass_patch_on_stone_center"]
  /// dirt_patch_on_stone_center — atlas position (384, 640), 64x64.
  let dirtPatchOnStone = byName["dirt_patch_on_stone_center"]
  /// sand_patch_on_stone_center — atlas position (704, 640), 64x64.
  let sandPatchOnStone = byName["sand_patch_on_stone_center"]

  // ── Groups (curated in the generator's input) ──
  let groundGrass = [| grass; grassB; grassC |]
  let groundDirt = [| dirt; dirtB; dirtC |]
  let groundSand = [| sand; sandB; sandC |]
  let groundStone = [| stone; stoneB; stoneC |]

  let grounds = [|
    grass
    grassB
    grassC
    dirt
    dirtB
    dirtC
    sand
    sandB
    sandC
    stone
    stoneB
    stoneC
  |]

  let pathDirt = [|
    pathVerticalDirt
    pathHorizontalDirt
    pathEndUpDirt
    pathEndLeftDirt
  |]

  let pathStone = [|
    pathVerticalStone
    pathHorizontalStone
    pathEndUpStone
    pathEndLeftStone
  |]

  let paths = [|
    pathVerticalDirt
    pathHorizontalDirt
    pathEndUpDirt
    pathEndLeftDirt
    pathVerticalStone
    pathHorizontalStone
    pathEndUpStone
    pathEndLeftStone
  |]

  let rocks = [| rockSmall; rockMedium; rockLarge |]
  let trees = [| treeRound; treePine |]
  let crates = [| crate; crateBeveled; container; containerLarge |]

  let props = [|
    bush
    rockSmall
    rockMedium
    rockLarge
    treeRound
    treePine
    crate
    crateBeveled
    container
    containerLarge
    coin
    turretMount
    turretBase
  |]

  let blendDots = [|
    grassDotOnDirt
    sandDotOnDirt
    stoneDotOnDirt
    dirtDotOnGrass
    sandDotOnGrass
    stoneDotOnGrass
    grassDotOnSand
    dirtDotOnSand
    stoneDotOnSand
    grassDotOnStone
    dirtDotOnStone
    sandDotOnStone
  |]

  let blendPatches = [|
    grassPatchOnDirt
    sandPatchOnDirt
    stonePatchOnDirt
    dirtPatchOnGrass
    sandPatchOnGrass
    stonePatchOnGrass
    grassPatchOnSand
    dirtPatchOnSand
    stonePatchOnSand
    grassPatchOnStone
    dirtPatchOnStone
    sandPatchOnStone
  |]
