// ─────────────────────────────────────────────────────────────
// GENERATED by BoneProbe emit — DO NOT EDIT BY HAND.
// Regenerate with:  dotnet run --project BoneProbe -- emit assets/kenney_tower_defense_kit/Models Defli3D/Shared/State/Models.fs
// Sources: E:/Mibo.Samples/assets/kenney_tower_defense_kit/Models/*.glb (110 models; snow-* excluded)
// ─────────────────────────────────────────────────────────────
namespace Defli3D.State

open System.Collections.Frozen
open System.Collections.Generic

// ModelInfo is hand-defined in Domain.fs (same role as Defli's TileInfo).

module Models =

  [<Literal>]
  let BasePath = "kenney_tower_defense_kit/Models"

  /// All models baked at compile time (mesh-local extents, sorted by name).
  /// Canonical store: ordered and iterable. The name index is built from it.
  let all: ModelInfo[] = [|
    {
      Name = "detail-crystal"
      Path = BasePath + "/detail-crystal"
      SizeX = 0.251f
      SizeY = 0.425f
      SizeZ = 0.29f
    }
    {
      Name = "detail-crystal-large"
      Path = BasePath + "/detail-crystal-large"
      SizeX = 0.892f
      SizeY = 0.552f
      SizeZ = 0.859f
    }
    {
      Name = "detail-dirt"
      Path = BasePath + "/detail-dirt"
      SizeX = 0.703f
      SizeY = 0.265f
      SizeZ = 0.712f
    }
    {
      Name = "detail-dirt-large"
      Path = BasePath + "/detail-dirt-large"
      SizeX = 0.853f
      SizeY = 0.415f
      SizeZ = 0.778f
    }
    {
      Name = "detail-rocks"
      Path = BasePath + "/detail-rocks"
      SizeX = 0.598f
      SizeY = 0.184f
      SizeZ = 0.605f
    }
    {
      Name = "detail-rocks-large"
      Path = BasePath + "/detail-rocks-large"
      SizeX = 0.892f
      SizeY = 0.415f
      SizeZ = 0.859f
    }
    {
      Name = "detail-tree"
      Path = BasePath + "/detail-tree"
      SizeX = 0.35f
      SizeY = 0.532f
      SizeZ = 0.35f
    }
    {
      Name = "detail-tree-large"
      Path = BasePath + "/detail-tree-large"
      SizeX = 0.5f
      SizeY = 0.76f
      SizeZ = 0.5f
    }
    {
      Name = "enemy-ufo-a"
      Path = BasePath + "/enemy-ufo-a"
      SizeX = 1.0f
      SizeY = 0.678f
      SizeZ = 1.0f
    }
    {
      Name = "enemy-ufo-a-weapon"
      Path = BasePath + "/enemy-ufo-a-weapon"
      SizeX = 1.0f
      SizeY = 0.522f
      SizeZ = 1.0f
    }
    {
      Name = "enemy-ufo-b"
      Path = BasePath + "/enemy-ufo-b"
      SizeX = 0.999f
      SizeY = 0.575f
      SizeZ = 1.0f
    }
    {
      Name = "enemy-ufo-b-weapon"
      Path = BasePath + "/enemy-ufo-b-weapon"
      SizeX = 0.999f
      SizeY = 0.684f
      SizeZ = 1.0f
    }
    {
      Name = "enemy-ufo-beam"
      Path = BasePath + "/enemy-ufo-beam"
      SizeX = 0.8f
      SizeY = 1.0f
      SizeZ = 0.8f
    }
    {
      Name = "enemy-ufo-beam-burst"
      Path = BasePath + "/enemy-ufo-beam-burst"
      SizeX = 1.052f
      SizeY = 1.0f
      SizeZ = 1.052f
    }
    {
      Name = "enemy-ufo-c"
      Path = BasePath + "/enemy-ufo-c"
      SizeX = 1.004f
      SizeY = 0.525f
      SizeZ = 1.0f
    }
    {
      Name = "enemy-ufo-c-weapon"
      Path = BasePath + "/enemy-ufo-c-weapon"
      SizeX = 1.004f
      SizeY = 0.721f
      SizeZ = 1.0f
    }
    {
      Name = "enemy-ufo-d"
      Path = BasePath + "/enemy-ufo-d"
      SizeX = 0.949f
      SizeY = 0.544f
      SizeZ = 0.95f
    }
    {
      Name = "enemy-ufo-d-weapon"
      Path = BasePath + "/enemy-ufo-d-weapon"
      SizeX = 0.949f
      SizeY = 0.66f
      SizeZ = 0.95f
    }
    {
      Name = "selection-a"
      Path = BasePath + "/selection-a"
      SizeX = 1.0f
      SizeY = 0.05f
      SizeZ = 1.0f
    }
    {
      Name = "selection-b"
      Path = BasePath + "/selection-b"
      SizeX = 1.0f
      SizeY = 0.2f
      SizeZ = 1.0f
    }
    {
      Name = "spawn-round"
      Path = BasePath + "/spawn-round"
      SizeX = 0.688f
      SizeY = 0.1f
      SizeZ = 0.688f
    }
    {
      Name = "spawn-square"
      Path = BasePath + "/spawn-square"
      SizeX = 0.688f
      SizeY = 0.1f
      SizeZ = 0.686f
    }
    {
      Name = "tile"
      Path = BasePath + "/tile"
      SizeX = 1.0f
      SizeY = 0.2f
      SizeZ = 1.0f
    }
    {
      Name = "tile-bump"
      Path = BasePath + "/tile-bump"
      SizeX = 1.0f
      SizeY = 0.3f
      SizeZ = 1.0f
    }
    {
      Name = "tile-corner-inner"
      Path = BasePath + "/tile-corner-inner"
      SizeX = 1.0f
      SizeY = 0.4f
      SizeZ = 1.0f
    }
    {
      Name = "tile-corner-large"
      Path = BasePath + "/tile-corner-large"
      SizeX = 2.0f
      SizeY = 0.96f
      SizeZ = 2.0f
    }
    {
      Name = "tile-corner-outer"
      Path = BasePath + "/tile-corner-outer"
      SizeX = 1.0f
      SizeY = 0.4f
      SizeZ = 1.0f
    }
    {
      Name = "tile-corner-round"
      Path = BasePath + "/tile-corner-round"
      SizeX = 1.0f
      SizeY = 0.296f
      SizeZ = 1.0f
    }
    {
      Name = "tile-corner-square"
      Path = BasePath + "/tile-corner-square"
      SizeX = 1.0f
      SizeY = 0.2f
      SizeZ = 1.0f
    }
    {
      Name = "tile-crossing"
      Path = BasePath + "/tile-crossing"
      SizeX = 1.0f
      SizeY = 0.2f
      SizeZ = 1.0f
    }
    {
      Name = "tile-crystal"
      Path = BasePath + "/tile-crystal"
      SizeX = 1.0f
      SizeY = 0.752f
      SizeZ = 1.0f
    }
    {
      Name = "tile-dirt"
      Path = BasePath + "/tile-dirt"
      SizeX = 1.0f
      SizeY = 0.1f
      SizeZ = 1.0f
    }
    {
      Name = "tile-end"
      Path = BasePath + "/tile-end"
      SizeX = 1.0f
      SizeY = 0.2f
      SizeZ = 1.0f
    }
    {
      Name = "tile-end-round"
      Path = BasePath + "/tile-end-round"
      SizeX = 1.0f
      SizeY = 0.2f
      SizeZ = 1.0f
    }
    {
      Name = "tile-hill"
      Path = BasePath + "/tile-hill"
      SizeX = 1.0f
      SizeY = 0.615f
      SizeZ = 1.0f
    }
    {
      Name = "tile-river-bridge"
      Path = BasePath + "/tile-river-bridge"
      SizeX = 1.0f
      SizeY = 0.3f
      SizeZ = 1.0f
    }
    {
      Name = "tile-river-corner"
      Path = BasePath + "/tile-river-corner"
      SizeX = 1.0f
      SizeY = 0.77f
      SizeZ = 1.0f
    }
    {
      Name = "tile-river-slope"
      Path = BasePath + "/tile-river-slope"
      SizeX = 1.0f
      SizeY = 0.45f
      SizeZ = 1.0f
    }
    {
      Name = "tile-river-slope-large"
      Path = BasePath + "/tile-river-slope-large"
      SizeX = 1.0f
      SizeY = 0.45f
      SizeZ = 2.0f
    }
    {
      Name = "tile-river-straight"
      Path = BasePath + "/tile-river-straight"
      SizeX = 1.0f
      SizeY = 0.25f
      SizeZ = 1.0f
    }
    {
      Name = "tile-river-transition"
      Path = BasePath + "/tile-river-transition"
      SizeX = 1.0f
      SizeY = 0.25f
      SizeZ = 1.0f
    }
    {
      Name = "tile-river-waterfall"
      Path = BasePath + "/tile-river-waterfall"
      SizeX = 1.0f
      SizeY = 0.45f
      SizeZ = 1.0f
    }
    {
      Name = "tile-rock"
      Path = BasePath + "/tile-rock"
      SizeX = 1.0f
      SizeY = 0.615f
      SizeZ = 1.0f
    }
    {
      Name = "tile-slope"
      Path = BasePath + "/tile-slope"
      SizeX = 1.0f
      SizeY = 0.4f
      SizeZ = 1.0f
    }
    {
      Name = "tile-spawn"
      Path = BasePath + "/tile-spawn"
      SizeX = 1.0f
      SizeY = 0.2f
      SizeZ = 1.0f
    }
    {
      Name = "tile-spawn-end"
      Path = BasePath + "/tile-spawn-end"
      SizeX = 1.0f
      SizeY = 0.2f
      SizeZ = 1.0f
    }
    {
      Name = "tile-spawn-end-round"
      Path = BasePath + "/tile-spawn-end-round"
      SizeX = 1.0f
      SizeY = 0.2f
      SizeZ = 1.0f
    }
    {
      Name = "tile-spawn-round"
      Path = BasePath + "/tile-spawn-round"
      SizeX = 1.0f
      SizeY = 0.2f
      SizeZ = 1.0f
    }
    {
      Name = "tile-split"
      Path = BasePath + "/tile-split"
      SizeX = 1.0f
      SizeY = 0.2f
      SizeZ = 1.0f
    }
    {
      Name = "tile-straight"
      Path = BasePath + "/tile-straight"
      SizeX = 1.0f
      SizeY = 0.2f
      SizeZ = 1.0f
    }
    {
      Name = "tile-straight-slope"
      Path = BasePath + "/tile-straight-slope"
      SizeX = 1.0f
      SizeY = 0.4f
      SizeZ = 1.0f
    }
    {
      Name = "tile-straight-slope-large"
      Path = BasePath + "/tile-straight-slope-large"
      SizeX = 1.0f
      SizeY = 0.4f
      SizeZ = 2.0f
    }
    {
      Name = "tile-transition"
      Path = BasePath + "/tile-transition"
      SizeX = 1.0f
      SizeY = 0.2f
      SizeZ = 1.0f
    }
    {
      Name = "tile-tree"
      Path = BasePath + "/tile-tree"
      SizeX = 1.0f
      SizeY = 0.96f
      SizeZ = 1.0f
    }
    {
      Name = "tile-tree-double"
      Path = BasePath + "/tile-tree-double"
      SizeX = 1.0f
      SizeY = 0.96f
      SizeZ = 1.0f
    }
    {
      Name = "tile-tree-quad"
      Path = BasePath + "/tile-tree-quad"
      SizeX = 1.0f
      SizeY = 0.96f
      SizeZ = 1.0f
    }
    {
      Name = "tile-wide-corner"
      Path = BasePath + "/tile-wide-corner"
      SizeX = 2.0f
      SizeY = 0.96f
      SizeZ = 2.0f
    }
    {
      Name = "tile-wide-split"
      Path = BasePath + "/tile-wide-split"
      SizeX = 2.0f
      SizeY = 0.2f
      SizeZ = 1.0f
    }
    {
      Name = "tile-wide-straight"
      Path = BasePath + "/tile-wide-straight"
      SizeX = 2.0f
      SizeY = 0.2f
      SizeZ = 1.0f
    }
    {
      Name = "tile-wide-transition"
      Path = BasePath + "/tile-wide-transition"
      SizeX = 2.0f
      SizeY = 0.2f
      SizeZ = 1.0f
    }
    {
      Name = "tower-round-base"
      Path = BasePath + "/tower-round-base"
      SizeX = 1.0f
      SizeY = 0.21f
      SizeZ = 1.0f
    }
    {
      Name = "tower-round-bottom-a"
      Path = BasePath + "/tower-round-bottom-a"
      SizeX = 1.0f
      SizeY = 0.6f
      SizeZ = 1.0f
    }
    {
      Name = "tower-round-bottom-b"
      Path = BasePath + "/tower-round-bottom-b"
      SizeX = 1.0f
      SizeY = 0.6f
      SizeZ = 1.0f
    }
    {
      Name = "tower-round-bottom-c"
      Path = BasePath + "/tower-round-bottom-c"
      SizeX = 1.0f
      SizeY = 0.6f
      SizeZ = 1.0f
    }
    {
      Name = "tower-round-build-a"
      Path = BasePath + "/tower-round-build-a"
      SizeX = 1.0f
      SizeY = 1.0f
      SizeZ = 1.0f
    }
    {
      Name = "tower-round-build-b"
      Path = BasePath + "/tower-round-build-b"
      SizeX = 1.0f
      SizeY = 1.0f
      SizeZ = 1.0f
    }
    {
      Name = "tower-round-build-c"
      Path = BasePath + "/tower-round-build-c"
      SizeX = 1.0f
      SizeY = 1.0f
      SizeZ = 1.0f
    }
    {
      Name = "tower-round-build-d"
      Path = BasePath + "/tower-round-build-d"
      SizeX = 1.0f
      SizeY = 1.79f
      SizeZ = 1.0f
    }
    {
      Name = "tower-round-build-e"
      Path = BasePath + "/tower-round-build-e"
      SizeX = 1.0f
      SizeY = 1.562f
      SizeZ = 1.0f
    }
    {
      Name = "tower-round-build-f"
      Path = BasePath + "/tower-round-build-f"
      SizeX = 1.0f
      SizeY = 1.79f
      SizeZ = 1.0f
    }
    {
      Name = "tower-round-crystals"
      Path = BasePath + "/tower-round-crystals"
      SizeX = 1.0f
      SizeY = 0.73f
      SizeZ = 1.0f
    }
    {
      Name = "tower-round-middle-a"
      Path = BasePath + "/tower-round-middle-a"
      SizeX = 1.108f
      SizeY = 0.6f
      SizeZ = 1.108f
    }
    {
      Name = "tower-round-middle-b"
      Path = BasePath + "/tower-round-middle-b"
      SizeX = 1.129f
      SizeY = 0.6f
      SizeZ = 1.243f
    }
    {
      Name = "tower-round-middle-c"
      Path = BasePath + "/tower-round-middle-c"
      SizeX = 1.15f
      SizeY = 0.6f
      SizeZ = 1.15f
    }
    {
      Name = "tower-round-roof-a"
      Path = BasePath + "/tower-round-roof-a"
      SizeX = 0.92f
      SizeY = 1.15f
      SizeZ = 0.92f
    }
    {
      Name = "tower-round-roof-b"
      Path = BasePath + "/tower-round-roof-b"
      SizeX = 1.0f
      SizeY = 1.29f
      SizeZ = 1.0f
    }
    {
      Name = "tower-round-roof-c"
      Path = BasePath + "/tower-round-roof-c"
      SizeX = 0.976f
      SizeY = 1.044f
      SizeZ = 0.976f
    }
    {
      Name = "tower-round-top-a"
      Path = BasePath + "/tower-round-top-a"
      SizeX = 0.92f
      SizeY = 0.5f
      SizeZ = 0.92f
    }
    {
      Name = "tower-round-top-b"
      Path = BasePath + "/tower-round-top-b"
      SizeX = 1.0f
      SizeY = 0.5f
      SizeZ = 1.0f
    }
    {
      Name = "tower-round-top-c"
      Path = BasePath + "/tower-round-top-c"
      SizeX = 0.976f
      SizeY = 0.532f
      SizeZ = 0.976f
    }
    {
      Name = "tower-square-bottom-a"
      Path = BasePath + "/tower-square-bottom-a"
      SizeX = 1.0f
      SizeY = 0.5f
      SizeZ = 1.0f
    }
    {
      Name = "tower-square-bottom-b"
      Path = BasePath + "/tower-square-bottom-b"
      SizeX = 1.0f
      SizeY = 0.5f
      SizeZ = 1.0f
    }
    {
      Name = "tower-square-bottom-c"
      Path = BasePath + "/tower-square-bottom-c"
      SizeX = 1.0f
      SizeY = 0.5f
      SizeZ = 1.0f
    }
    {
      Name = "tower-square-build-a"
      Path = BasePath + "/tower-square-build-a"
      SizeX = 1.1f
      SizeY = 1.0f
      SizeZ = 1.1f
    }
    {
      Name = "tower-square-build-b"
      Path = BasePath + "/tower-square-build-b"
      SizeX = 1.1f
      SizeY = 1.0f
      SizeZ = 1.1f
    }
    {
      Name = "tower-square-build-c"
      Path = BasePath + "/tower-square-build-c"
      SizeX = 1.0f
      SizeY = 1.0f
      SizeZ = 1.0f
    }
    {
      Name = "tower-square-build-d"
      Path = BasePath + "/tower-square-build-d"
      SizeX = 1.1f
      SizeY = 1.775f
      SizeZ = 1.1f
    }
    {
      Name = "tower-square-build-e"
      Path = BasePath + "/tower-square-build-e"
      SizeX = 1.1f
      SizeY = 1.739f
      SizeZ = 1.1f
    }
    {
      Name = "tower-square-build-f"
      Path = BasePath + "/tower-square-build-f"
      SizeX = 1.0f
      SizeY = 1.715f
      SizeZ = 1.0f
    }
    {
      Name = "tower-square-middle-a"
      Path = BasePath + "/tower-square-middle-a"
      SizeX = 1.1f
      SizeY = 0.5f
      SizeZ = 1.1f
    }
    {
      Name = "tower-square-middle-b"
      Path = BasePath + "/tower-square-middle-b"
      SizeX = 1.0f
      SizeY = 0.5f
      SizeZ = 1.0f
    }
    {
      Name = "tower-square-middle-c"
      Path = BasePath + "/tower-square-middle-c"
      SizeX = 1.0f
      SizeY = 0.5f
      SizeZ = 1.0f
    }
    {
      Name = "tower-square-roof-a"
      Path = BasePath + "/tower-square-roof-a"
      SizeX = 1.1f
      SizeY = 1.275f
      SizeZ = 1.1f
    }
    {
      Name = "tower-square-roof-b"
      Path = BasePath + "/tower-square-roof-b"
      SizeX = 1.1f
      SizeY = 1.239f
      SizeZ = 1.1f
    }
    {
      Name = "tower-square-roof-c"
      Path = BasePath + "/tower-square-roof-c"
      SizeX = 1.0f
      SizeY = 1.215f
      SizeZ = 1.0f
    }
    {
      Name = "tower-square-top-a"
      Path = BasePath + "/tower-square-top-a"
      SizeX = 1.1f
      SizeY = 0.5f
      SizeZ = 1.1f
    }
    {
      Name = "tower-square-top-b"
      Path = BasePath + "/tower-square-top-b"
      SizeX = 1.1f
      SizeY = 0.5f
      SizeZ = 1.1f
    }
    {
      Name = "tower-square-top-c"
      Path = BasePath + "/tower-square-top-c"
      SizeX = 1.0f
      SizeY = 0.5f
      SizeZ = 1.0f
    }
    {
      Name = "weapon-ammo-arrow"
      Path = BasePath + "/weapon-ammo-arrow"
      SizeX = 0.16f
      SizeY = 0.16f
      SizeZ = 0.778f
    }
    {
      Name = "weapon-ammo-boulder"
      Path = BasePath + "/weapon-ammo-boulder"
      SizeX = 0.32f
      SizeY = 0.24f
      SizeZ = 0.277f
    }
    {
      Name = "weapon-ammo-bullet"
      Path = BasePath + "/weapon-ammo-bullet"
      SizeX = 0.2f
      SizeY = 0.2f
      SizeZ = 0.3f
    }
    {
      Name = "weapon-ammo-cannonball"
      Path = BasePath + "/weapon-ammo-cannonball"
      SizeX = 0.28f
      SizeY = 0.28f
      SizeZ = 0.28f
    }
    {
      Name = "weapon-ballista"
      Path = BasePath + "/weapon-ballista"
      SizeX = 0.663f
      SizeY = 0.53f
      SizeZ = 0.789f
    }
    {
      Name = "weapon-cannon"
      Path = BasePath + "/weapon-cannon"
      SizeX = 0.6f
      SizeY = 0.59f
      SizeZ = 0.6f
    }
    {
      Name = "weapon-catapult"
      Path = BasePath + "/weapon-catapult"
      SizeX = 0.6f
      SizeY = 0.54f
      SizeZ = 0.837f
    }
    {
      Name = "weapon-turret"
      Path = BasePath + "/weapon-turret"
      SizeX = 0.511f
      SizeY = 0.3f
      SizeZ = 0.617f
    }
    {
      Name = "wood-structure"
      Path = BasePath + "/wood-structure"
      SizeX = 1.0f
      SizeY = 0.5f
      SizeZ = 1.0f
    }
    {
      Name = "wood-structure-high"
      Path = BasePath + "/wood-structure-high"
      SizeX = 1.0f
      SizeY = 1.0f
      SizeZ = 1.0f
    }
    {
      Name = "wood-structure-high-part"
      Path = BasePath + "/wood-structure-high-part"
      SizeX = 1.0f
      SizeY = 1.0f
      SizeZ = 0.128f
    }
    {
      Name = "wood-structure-part"
      Path = BasePath + "/wood-structure-part"
      SizeX = 1.0f
      SizeY = 0.5f
      SizeZ = 0.128f
    }
  |]

  /// O(1) name index over the baked dataset (built once at module init).
  let byName: FrozenDictionary<string, ModelInfo> =
    all
    |> Seq.map(fun t -> KeyValuePair(t.Name, t))
    |> FrozenDictionary.ToFrozenDictionary

  /// Safe name lookup for data-driven code (tower/enemy defs, procedural gen).
  let inline tryByName(name: string) : ModelInfo voption =
    Defli3D.FrozenDict.tryGetValue name byName

  // ── Semantically named models (curated in the generator) ──

  /// tile — 1.0f × 0.2f × 1.0f.
  let tileGrass = byName["tile"]
  /// tile-dirt — 1.0f × 0.1f × 1.0f.
  let tileDirt = byName["tile-dirt"]
  /// tile-rock — 1.0f × 0.615f × 1.0f.
  let tileRock = byName["tile-rock"]
  /// tile-bump — 1.0f × 0.3f × 1.0f.
  let tileBump = byName["tile-bump"]
  /// tile-hill — 1.0f × 0.615f × 1.0f.
  let tileHill = byName["tile-hill"]
  /// tile-crystal — 1.0f × 0.752f × 1.0f.
  let tileCrystal = byName["tile-crystal"]
  /// tile-slope — 1.0f × 0.4f × 1.0f.
  let tileSlope = byName["tile-slope"]
  /// tile-tree — 1.0f × 0.96f × 1.0f.
  let tileTree = byName["tile-tree"]
  /// tile-tree-double — 1.0f × 0.96f × 1.0f.
  let tileTreeDouble = byName["tile-tree-double"]
  /// tile-tree-quad — 1.0f × 0.96f × 1.0f.
  let tileTreeQuad = byName["tile-tree-quad"]
  /// tile-straight — 1.0f × 0.2f × 1.0f.
  let roadStraight = byName["tile-straight"]
  /// tile-corner-round — 1.0f × 0.296f × 1.0f.
  let roadCornerRound = byName["tile-corner-round"]
  /// tile-corner-square — 1.0f × 0.2f × 1.0f.
  let roadCornerSquare = byName["tile-corner-square"]
  /// tile-crossing — 1.0f × 0.2f × 1.0f.
  let roadCrossing = byName["tile-crossing"]
  /// tile-end — 1.0f × 0.2f × 1.0f.
  let roadEnd = byName["tile-end"]
  /// tile-end-round — 1.0f × 0.2f × 1.0f.
  let roadEndRound = byName["tile-end-round"]
  /// tile-split — 1.0f × 0.2f × 1.0f.
  let roadSplit = byName["tile-split"]
  /// tile-transition — 1.0f × 0.2f × 1.0f.
  let roadTransition = byName["tile-transition"]
  /// tile-spawn — 1.0f × 0.2f × 1.0f.
  let tileSpawn = byName["tile-spawn"]
  /// tile-spawn-round — 1.0f × 0.2f × 1.0f.
  let tileSpawnRound = byName["tile-spawn-round"]
  /// tile-spawn-end — 1.0f × 0.2f × 1.0f.
  let tileSpawnEnd = byName["tile-spawn-end"]
  /// tile-spawn-end-round — 1.0f × 0.2f × 1.0f.
  let tileSpawnEndRound = byName["tile-spawn-end-round"]
  /// spawn-round — 0.688f × 0.1f × 0.688f.
  let spawnRound = byName["spawn-round"]
  /// spawn-square — 0.688f × 0.1f × 0.686f.
  let spawnSquare = byName["spawn-square"]
  /// tower-round-base — 1.0f × 0.21f × 1.0f.
  let towerRoundBase = byName["tower-round-base"]
  /// tower-round-bottom-a — 1.0f × 0.6f × 1.0f.
  let towerRoundBottomA = byName["tower-round-bottom-a"]
  /// tower-round-bottom-b — 1.0f × 0.6f × 1.0f.
  let towerRoundBottomB = byName["tower-round-bottom-b"]
  /// tower-round-bottom-c — 1.0f × 0.6f × 1.0f.
  let towerRoundBottomC = byName["tower-round-bottom-c"]
  /// tower-round-middle-a — 1.108f × 0.6f × 1.108f.
  let towerRoundMiddleA = byName["tower-round-middle-a"]
  /// tower-round-middle-b — 1.129f × 0.6f × 1.243f.
  let towerRoundMiddleB = byName["tower-round-middle-b"]
  /// tower-round-middle-c — 1.15f × 0.6f × 1.15f.
  let towerRoundMiddleC = byName["tower-round-middle-c"]
  /// tower-round-top-a — 0.92f × 0.5f × 0.92f.
  let towerRoundTopA = byName["tower-round-top-a"]
  /// tower-round-top-b — 1.0f × 0.5f × 1.0f.
  let towerRoundTopB = byName["tower-round-top-b"]
  /// tower-round-top-c — 0.976f × 0.532f × 0.976f.
  let towerRoundTopC = byName["tower-round-top-c"]
  /// tower-round-roof-a — 0.92f × 1.15f × 0.92f.
  let towerRoundRoofA = byName["tower-round-roof-a"]
  /// tower-round-roof-b — 1.0f × 1.29f × 1.0f.
  let towerRoundRoofB = byName["tower-round-roof-b"]
  /// tower-round-roof-c — 0.976f × 1.044f × 0.976f.
  let towerRoundRoofC = byName["tower-round-roof-c"]
  /// tower-round-build-a — 1.0f × 1.0f × 1.0f.
  let towerRoundBuildA = byName["tower-round-build-a"]
  /// tower-round-build-b — 1.0f × 1.0f × 1.0f.
  let towerRoundBuildB = byName["tower-round-build-b"]
  /// tower-round-build-c — 1.0f × 1.0f × 1.0f.
  let towerRoundBuildC = byName["tower-round-build-c"]
  /// tower-round-build-d — 1.0f × 1.79f × 1.0f.
  let towerRoundBuildD = byName["tower-round-build-d"]
  /// tower-round-build-e — 1.0f × 1.562f × 1.0f.
  let towerRoundBuildE = byName["tower-round-build-e"]
  /// tower-round-build-f — 1.0f × 1.79f × 1.0f.
  let towerRoundBuildF = byName["tower-round-build-f"]
  /// tower-square-bottom-a — 1.0f × 0.5f × 1.0f.
  let towerSquareBottomA = byName["tower-square-bottom-a"]
  /// tower-square-bottom-b — 1.0f × 0.5f × 1.0f.
  let towerSquareBottomB = byName["tower-square-bottom-b"]
  /// tower-square-bottom-c — 1.0f × 0.5f × 1.0f.
  let towerSquareBottomC = byName["tower-square-bottom-c"]
  /// tower-square-middle-a — 1.1f × 0.5f × 1.1f.
  let towerSquareMiddleA = byName["tower-square-middle-a"]
  /// tower-square-middle-b — 1.0f × 0.5f × 1.0f.
  let towerSquareMiddleB = byName["tower-square-middle-b"]
  /// tower-square-middle-c — 1.0f × 0.5f × 1.0f.
  let towerSquareMiddleC = byName["tower-square-middle-c"]
  /// tower-square-top-a — 1.1f × 0.5f × 1.1f.
  let towerSquareTopA = byName["tower-square-top-a"]
  /// tower-square-top-b — 1.1f × 0.5f × 1.1f.
  let towerSquareTopB = byName["tower-square-top-b"]
  /// tower-square-top-c — 1.0f × 0.5f × 1.0f.
  let towerSquareTopC = byName["tower-square-top-c"]
  /// tower-square-roof-a — 1.1f × 1.275f × 1.1f.
  let towerSquareRoofA = byName["tower-square-roof-a"]
  /// tower-square-roof-b — 1.1f × 1.239f × 1.1f.
  let towerSquareRoofB = byName["tower-square-roof-b"]
  /// tower-square-roof-c — 1.0f × 1.215f × 1.0f.
  let towerSquareRoofC = byName["tower-square-roof-c"]
  /// tower-square-build-a — 1.1f × 1.0f × 1.1f.
  let towerSquareBuildA = byName["tower-square-build-a"]
  /// tower-square-build-b — 1.1f × 1.0f × 1.1f.
  let towerSquareBuildB = byName["tower-square-build-b"]
  /// tower-square-build-c — 1.0f × 1.0f × 1.0f.
  let towerSquareBuildC = byName["tower-square-build-c"]
  /// tower-square-build-d — 1.1f × 1.775f × 1.1f.
  let towerSquareBuildD = byName["tower-square-build-d"]
  /// tower-square-build-e — 1.1f × 1.739f × 1.1f.
  let towerSquareBuildE = byName["tower-square-build-e"]
  /// tower-square-build-f — 1.0f × 1.715f × 1.0f.
  let towerSquareBuildF = byName["tower-square-build-f"]
  /// weapon-ballista — 0.663f × 0.53f × 0.789f.
  let weaponBallista = byName["weapon-ballista"]
  /// weapon-cannon — 0.6f × 0.59f × 0.6f.
  let weaponCannon = byName["weapon-cannon"]
  /// weapon-catapult — 0.6f × 0.54f × 0.837f.
  let weaponCatapult = byName["weapon-catapult"]
  /// weapon-turret — 0.511f × 0.3f × 0.617f.
  let weaponTurret = byName["weapon-turret"]
  /// weapon-ammo-arrow — 0.16f × 0.16f × 0.778f.
  let ammoArrow = byName["weapon-ammo-arrow"]
  /// weapon-ammo-boulder — 0.32f × 0.24f × 0.277f.
  let ammoBoulder = byName["weapon-ammo-boulder"]
  /// weapon-ammo-bullet — 0.2f × 0.2f × 0.3f.
  let ammoBullet = byName["weapon-ammo-bullet"]
  /// weapon-ammo-cannonball — 0.28f × 0.28f × 0.28f.
  let ammoCannonball = byName["weapon-ammo-cannonball"]
  /// enemy-ufo-a — 1.0f × 0.678f × 1.0f.
  let enemyUfoA = byName["enemy-ufo-a"]
  /// enemy-ufo-b — 0.999f × 0.575f × 1.0f.
  let enemyUfoB = byName["enemy-ufo-b"]
  /// enemy-ufo-c — 1.004f × 0.525f × 1.0f.
  let enemyUfoC = byName["enemy-ufo-c"]
  /// enemy-ufo-d — 0.949f × 0.544f × 0.95f.
  let enemyUfoD = byName["enemy-ufo-d"]
  /// enemy-ufo-a-weapon — 1.0f × 0.522f × 1.0f.
  let enemyUfoAWeapon = byName["enemy-ufo-a-weapon"]
  /// enemy-ufo-b-weapon — 0.999f × 0.684f × 1.0f.
  let enemyUfoBWeapon = byName["enemy-ufo-b-weapon"]
  /// enemy-ufo-c-weapon — 1.004f × 0.721f × 1.0f.
  let enemyUfoCWeapon = byName["enemy-ufo-c-weapon"]
  /// enemy-ufo-d-weapon — 0.949f × 0.66f × 0.95f.
  let enemyUfoDWeapon = byName["enemy-ufo-d-weapon"]
  /// enemy-ufo-beam — 0.8f × 1.0f × 0.8f.
  let enemyUfoBeam = byName["enemy-ufo-beam"]
  /// enemy-ufo-beam-burst — 1.052f × 1.0f × 1.052f.
  let enemyUfoBeamBurst = byName["enemy-ufo-beam-burst"]
  /// detail-crystal — 0.251f × 0.425f × 0.29f.
  let detailCrystal = byName["detail-crystal"]
  /// detail-crystal-large — 0.892f × 0.552f × 0.859f.
  let detailCrystalLarge = byName["detail-crystal-large"]
  /// detail-dirt — 0.703f × 0.265f × 0.712f.
  let detailDirt = byName["detail-dirt"]
  /// detail-dirt-large — 0.853f × 0.415f × 0.778f.
  let detailDirtLarge = byName["detail-dirt-large"]
  /// detail-rocks — 0.598f × 0.184f × 0.605f.
  let detailRocks = byName["detail-rocks"]
  /// detail-rocks-large — 0.892f × 0.415f × 0.859f.
  let detailRocksLarge = byName["detail-rocks-large"]
  /// detail-tree — 0.35f × 0.532f × 0.35f.
  let detailTree = byName["detail-tree"]
  /// detail-tree-large — 0.5f × 0.76f × 0.5f.
  let detailTreeLarge = byName["detail-tree-large"]
  /// wood-structure — 1.0f × 0.5f × 1.0f.
  let woodStructure = byName["wood-structure"]
  /// wood-structure-high — 1.0f × 1.0f × 1.0f.
  let woodStructureHigh = byName["wood-structure-high"]
  /// selection-a — 1.0f × 0.05f × 1.0f.
  let selectionA = byName["selection-a"]
  /// selection-b — 1.0f × 0.2f × 1.0f.
  let selectionB = byName["selection-b"]

  // ── Groups (curated in the generator) ──

  let groundTiles = [|
    tileGrass
    tileDirt
    tileRock
    tileBump
    tileHill
    tileCrystal
    tileSlope
    tileTree
    tileTreeDouble
    tileTreeQuad
  |]

  let roadTiles = [|
    roadStraight
    roadCornerRound
    roadCornerSquare
    roadCrossing
    roadEnd
    roadEndRound
    roadSplit
    roadTransition
  |]

  let spawnTiles = [|
    tileSpawn
    tileSpawnRound
    tileSpawnEnd
    tileSpawnEndRound
    spawnRound
    spawnSquare
  |]

  let towerRoundParts = [|
    towerRoundBase
    towerRoundBottomA
    towerRoundBottomB
    towerRoundBottomC
    towerRoundMiddleA
    towerRoundMiddleB
    towerRoundMiddleC
    towerRoundTopA
    towerRoundTopB
    towerRoundTopC
    towerRoundRoofA
    towerRoundRoofB
    towerRoundRoofC
    towerRoundBuildA
    towerRoundBuildB
    towerRoundBuildC
    towerRoundBuildD
    towerRoundBuildE
    towerRoundBuildF
  |]

  let towerSquareParts = [|
    towerSquareBottomA
    towerSquareBottomB
    towerSquareBottomC
    towerSquareMiddleA
    towerSquareMiddleB
    towerSquareMiddleC
    towerSquareTopA
    towerSquareTopB
    towerSquareTopC
    towerSquareRoofA
    towerSquareRoofB
    towerSquareRoofC
    towerSquareBuildA
    towerSquareBuildB
    towerSquareBuildC
    towerSquareBuildD
    towerSquareBuildE
    towerSquareBuildF
  |]

  let weapons = [| weaponBallista; weaponCannon; weaponCatapult; weaponTurret |]
  let ammo = [| ammoArrow; ammoBoulder; ammoBullet; ammoCannonball |]
  let enemies = [| enemyUfoA; enemyUfoB; enemyUfoC; enemyUfoD |]

  let enemyWeapons = [|
    enemyUfoAWeapon
    enemyUfoBWeapon
    enemyUfoCWeapon
    enemyUfoDWeapon
  |]

  let decorations = [|
    detailCrystal
    detailCrystalLarge
    detailDirt
    detailDirtLarge
    detailRocks
    detailRocksLarge
    detailTree
    detailTreeLarge
    woodStructure
    woodStructureHigh
  |]

  let selectionRings = [| selectionA; selectionB |]
