// ─────────────────────────────────────────────────────────────
// GENERATED by tools/gen-tiles.fsx — DO NOT EDIT BY HAND.
// Regenerate with:  dotnet fsi tools/gen-tiles.fsx
// Sources: assets/kenney_tower-defense-top-down/towerDefense_tilesheet.xml,
//          assets/kenney_top-down-tanks-remastered/allSprites_default.xml
// ─────────────────────────────────────────────────────────────
namespace Defli.State

open System.Collections.Frozen
open System.Collections.Generic

module Tiles =

  [<Literal>]
  let SheetPath = "kenney_tower-defense-top-down/towerDefense_tilesheet.png"

  [<Literal>]
  let TileSize = 64

  /// All 299 atlas tiles (name, position, size) baked at compile time.
  /// Canonical store: ordered and iterable. The name index is built from it.
  let all: TileInfo[] = [|
    {
      Name = "grass_patch_on_dirt_top_left"
      X = 0
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_top"
      X = 64
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_top_right"
      X = 128
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_grass_top_left"
      X = 192
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_grass_top_right"
      X = 256
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_top_left"
      X = 320
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_top"
      X = 384
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_top_right"
      X = 448
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_sand_top_left"
      X = 512
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_sand_top_right"
      X = 576
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_top_left"
      X = 640
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_top"
      X = 704
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_top_right"
      X = 768
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_stone_top_left"
      X = 832
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_stone_top_right"
      X = 896
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "button_white"
      X = 960
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "button_white_wrench"
      X = 1024
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "button_white_close"
      X = 1088
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "button_white_target"
      X = 1152
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "effect_impact_ring"
      X = 1216
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "effect_impact_debris"
      X = 1280
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "effect_impact_burst"
      X = 1344
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "crosshair"
      X = 1408
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_left"
      X = 0
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_center"
      X = 64
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_right"
      X = 128
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_grass_bottom_left"
      X = 192
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_grass_bottom_right"
      X = 256
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_left"
      X = 320
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_center"
      X = 384
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_right"
      X = 448
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_sand_bottom_left"
      X = 512
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_sand_bottom_right"
      X = 576
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_left"
      X = 640
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_center"
      X = 704
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_right"
      X = 768
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_stone_bottom_left"
      X = 832
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_stone_bottom_right"
      X = 896
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green"
      X = 960
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green_wrench"
      X = 1024
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green_close"
      X = 1088
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green_target"
      X = 1152
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green_alt"
      X = 1216
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green_wrench_alt"
      X = 1280
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green_close_alt"
      X = 1344
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green_target_alt"
      X = 1408
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_bottom_left"
      X = 0
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_bottom"
      X = 64
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_bottom_right"
      X = 128
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "grass_dot_on_dirt"
      X = 192
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_full_a"
      X = 256
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_bottom_left"
      X = 320
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_bottom"
      X = 384
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_bottom_right"
      X = 448
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "sand_dot_on_dirt"
      X = 512
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_full_b"
      X = 576
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_bottom_left"
      X = 640
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_bottom"
      X = 704
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_bottom_right"
      X = 768
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "stone_dot_on_dirt"
      X = 832
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_full_c"
      X = 896
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown"
      X = 960
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown_wrench"
      X = 1024
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown_close"
      X = 1088
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown_target"
      X = 1152
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown_alt"
      X = 1216
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown_wrench_alt"
      X = 1280
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown_close_alt"
      X = 1344
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown_target_alt"
      X = 1408
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_top_left"
      X = 0
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_top"
      X = 64
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_top_right"
      X = 128
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_dirt_top_left"
      X = 192
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_dirt_top_right"
      X = 256
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_top_left"
      X = 320
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_top"
      X = 384
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_top_right"
      X = 448
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_sand_top_left"
      X = 512
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_sand_top_right"
      X = 576
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_top_left"
      X = 640
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_top"
      X = 704
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_top_right"
      X = 768
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_stone_top_left"
      X = 832
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_stone_top_right"
      X = 896
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel"
      X = 960
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel_wrench"
      X = 1024
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel_close"
      X = 1088
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel_target"
      X = 1152
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel_alt"
      X = 1216
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel_wrench_alt"
      X = 1280
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel_close_alt"
      X = 1344
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel_target_alt"
      X = 1408
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_left"
      X = 0
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_center"
      X = 64
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_right"
      X = 128
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_dirt_bottom_left"
      X = 192
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_dirt_bottom_right"
      X = 256
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_left"
      X = 320
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_center"
      X = 384
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_right"
      X = 448
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_sand_bottom_left"
      X = 512
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_sand_bottom_right"
      X = 576
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_left"
      X = 640
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_center"
      X = 704
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_right"
      X = 768
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_stone_bottom_left"
      X = 832
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_stone_bottom_right"
      X = 896
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige"
      X = 960
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige_wrench"
      X = 1024
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige_close"
      X = 1088
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige_target"
      X = 1152
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige_alt"
      X = 1216
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige_wrench_alt"
      X = 1280
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige_close_alt"
      X = 1344
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige_target_alt"
      X = 1408
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_bottom_left"
      X = 0
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_bottom"
      X = 64
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_bottom_right"
      X = 128
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_dot_on_grass"
      X = 192
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "grass_full_a"
      X = 256
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_bottom_left"
      X = 320
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_bottom"
      X = 384
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_bottom_right"
      X = 448
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "sand_dot_on_grass"
      X = 512
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "grass_full_b"
      X = 576
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_bottom_left"
      X = 640
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_bottom"
      X = 704
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_bottom_right"
      X = 768
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "stone_dot_on_grass"
      X = 832
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "grass_full_c"
      X = 896
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "tree_large"
      X = 960
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "bush_small"
      X = 1024
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "plant_sprig"
      X = 1088
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "tree_round"
      X = 1152
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "tree_pine"
      X = 1216
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "rock_small"
      X = 1280
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "rock_large"
      X = 1344
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "rock_medium"
      X = 1408
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_top_left"
      X = 0
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_top"
      X = 64
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_top_right"
      X = 128
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_grass_top_left"
      X = 192
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_grass_top_right"
      X = 256
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_top_left"
      X = 320
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_top"
      X = 384
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_top_right"
      X = 448
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_dirt_top_left"
      X = 512
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_dirt_top_right"
      X = 576
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_top_left"
      X = 640
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_top"
      X = 704
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_top_right"
      X = 768
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_stone_top_left"
      X = 832
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_stone_top_right"
      X = 896
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_up_grass"
      X = 960
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_up_dirt"
      X = 1024
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_up_stone"
      X = 1088
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_up_sand"
      X = 1152
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "grass_full_textured"
      X = 1216
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_full_textured"
      X = 1280
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "stone_full_textured"
      X = 1344
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "sand_full_textured"
      X = 1408
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_left"
      X = 0
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_center"
      X = 64
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_right"
      X = 128
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_grass_bottom_left"
      X = 192
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_grass_bottom_right"
      X = 256
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_left"
      X = 320
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_center"
      X = 384
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_right"
      X = 448
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_dirt_bottom_left"
      X = 512
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_dirt_bottom_right"
      X = 576
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_left"
      X = 640
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_center"
      X = 704
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_right"
      X = 768
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_stone_bottom_left"
      X = 832
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_stone_bottom_right"
      X = 896
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "path_vertical_grass"
      X = 960
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "path_vertical_dirt"
      X = 1024
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "path_vertical_stone"
      X = 1088
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "path_vertical_sand"
      X = 1152
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "crate_metal_square"
      X = 1216
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "crate_metal_octagon"
      X = 1280
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "crate_metal_beveled"
      X = 1344
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "crate_metal_diamond"
      X = 1408
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_bottom_left"
      X = 0
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_bottom"
      X = 64
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_bottom_right"
      X = 128
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "grass_dot_on_sand"
      X = 192
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "sand_full_a"
      X = 256
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_bottom_left"
      X = 320
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_bottom"
      X = 384
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_bottom_right"
      X = 448
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_dot_on_sand"
      X = 512
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "sand_full_b"
      X = 576
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_bottom_left"
      X = 640
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_bottom"
      X = 704
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_bottom_right"
      X = 768
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "stone_dot_on_sand"
      X = 832
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "sand_full_c"
      X = 896
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_left_grass"
      X = 960
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_left_dirt"
      X = 1024
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_left_stone"
      X = 1088
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_left_sand"
      X = 1152
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "turret_mount_empty"
      X = 1216
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "turret_missiles_dual"
      X = 1280
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "rocket_pod_dual"
      X = 1344
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "rocket_pod_single"
      X = 1408
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_top_left"
      X = 0
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_top"
      X = 64
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_top_right"
      X = 128
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_grass_top_left"
      X = 192
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_grass_top_right"
      X = 256
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_top_left"
      X = 320
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_top"
      X = 384
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_top_right"
      X = 448
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_dirt_top_left"
      X = 512
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_dirt_top_right"
      X = 576
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_top_left"
      X = 640
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_top"
      X = 704
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_top_right"
      X = 768
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_sand_top_left"
      X = 832
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_sand_top_right"
      X = 896
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "path_horizontal_grass"
      X = 960
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "path_horizontal_dirt"
      X = 1024
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "path_horizontal_stone"
      X = 1088
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "path_horizontal_sand"
      X = 1152
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "turret_base_a"
      X = 1216
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "turret_base_b"
      X = 1280
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "container_large"
      X = 1344
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "container_small"
      X = 1408
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_left"
      X = 0
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_center"
      X = 64
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_right"
      X = 128
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_grass_bottom_left"
      X = 192
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_grass_bottom_right"
      X = 256
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_left"
      X = 320
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_center"
      X = 384
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_right"
      X = 448
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_dirt_bottom_left"
      X = 512
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_dirt_bottom_right"
      X = 576
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_left"
      X = 640
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_center"
      X = 704
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_right"
      X = 768
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_sand_bottom_left"
      X = 832
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_sand_bottom_right"
      X = 896
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "soldier_green"
      X = 960
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "soldier_slate"
      X = 1024
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "soldier_brown"
      X = 1088
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "soldier_gray"
      X = 1152
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "turret_green"
      X = 1216
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "turret_red_dual"
      X = 1280
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "rocket_small"
      X = 1344
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "rocket_large"
      X = 1408
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_bottom_left"
      X = 0
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_bottom"
      X = 64
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_bottom_right"
      X = 128
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "grass_dot_on_stone"
      X = 192
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "stone_full_a"
      X = 256
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_bottom_left"
      X = 320
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_bottom"
      X = 384
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_bottom_right"
      X = 448
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_dot_on_stone"
      X = 512
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "stone_full_b"
      X = 576
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_bottom_left"
      X = 640
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_bottom"
      X = 704
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_bottom_right"
      X = 768
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "sand_dot_on_stone"
      X = 832
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "stone_full_c"
      X = 896
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "tank_hull_green"
      X = 961
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "tank_hull_beige"
      X = 1025
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "plane_green"
      X = 1088
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "plane_gray"
      X = 1152
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "coin_gold"
      X = 1216
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "coin_gold_rimmed"
      X = 1280
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "coin_copper"
      X = 1344
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "coin_silver"
      X = 1408
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "digit_0"
      X = 0
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_1"
      X = 64
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_2"
      X = 128
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_3"
      X = 192
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_4"
      X = 256
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_5"
      X = 320
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_6"
      X = 384
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_7"
      X = 448
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_8"
      X = 512
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_9"
      X = 576
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "symbol_percent"
      X = 640
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "symbol_dollar"
      X = 704
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "symbol_colon"
      X = 768
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "symbol_plus"
      X = 832
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "symbol_period"
      X = 896
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "tank_turret_green"
      X = 960
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "tank_turret_beige"
      X = 1024
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "plane_ghost_a"
      X = 1088
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "plane_ghost_b"
      X = 1152
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "flame_small"
      X = 1216
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "flame_large"
      X = 1280
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "flame_thin"
      X = 1344
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "flame_spread"
      X = 1408
      Y = 768
      Width = 64
      Height = 64
    }
  |]

  /// O(1) name index over the baked dataset (built once at module init).
  let byName: FrozenDictionary<string, TileInfo> =
    all
    |> Seq.map(fun t -> KeyValuePair(t.Name, t))
    |> FrozenDictionary.ToFrozenDictionary

  /// Safe name lookup for data-driven code (tower/enemy defs, procedural gen).
  let tryByName(name: string) : TileInfo voption =
    Defli.FrozenDict.tryGetValue name byName

  // ── Semantically named tiles (curated in the generator) ──
  /// grass_full_a — atlas position (256, 320), 64x64.
  let grassFullA = byName["grass_full_a"]
  /// grass_full_b — atlas position (576, 320), 64x64.
  let grassFullB = byName["grass_full_b"]
  /// grass_full_c — atlas position (896, 320), 64x64.
  let grassFullC = byName["grass_full_c"]
  /// dirt_full_a — atlas position (256, 128), 64x64.
  let dirtFullA = byName["dirt_full_a"]
  /// dirt_full_b — atlas position (576, 128), 64x64.
  let dirtFullB = byName["dirt_full_b"]
  /// dirt_full_c — atlas position (896, 128), 64x64.
  let dirtFullC = byName["dirt_full_c"]
  /// path_vertical_dirt — atlas position (1024, 448), 64x64.
  let pathVerticalDirt = byName["path_vertical_dirt"]
  /// path_horizontal_dirt — atlas position (1024, 576), 64x64.
  let pathHorizontalDirt = byName["path_horizontal_dirt"]
  /// path_end_up_dirt — atlas position (1024, 384), 64x64.
  let pathEndUpDirt = byName["path_end_up_dirt"]
  /// path_end_left_dirt — atlas position (1024, 512), 64x64.
  let pathEndLeftDirt = byName["path_end_left_dirt"]
  /// turret_mount_empty — atlas position (1216, 512), 64x64.
  let turretMountEmpty = byName["turret_mount_empty"]
  /// turret_base_a — atlas position (1216, 576), 64x64.
  let turretBaseA = byName["turret_base_a"]
  /// turret_green — atlas position (1216, 640), 64x64.
  let turretGreen = byName["turret_green"]
  /// turret_red_dual — atlas position (1280, 640), 64x64.
  let turretRedDual = byName["turret_red_dual"]
  /// turret_missiles_dual — atlas position (1280, 512), 64x64.
  let turretMissilesDual = byName["turret_missiles_dual"]
  /// tank_turret_green — atlas position (960, 768), 64x64.
  let tankTurretGreen = byName["tank_turret_green"]
  /// tank_turret_beige — atlas position (1024, 768), 64x64.
  let tankTurretBeige = byName["tank_turret_beige"]
  /// tank_hull_green — atlas position (961, 704), 64x64.
  let tankHullGreen = byName["tank_hull_green"]
  /// tank_hull_beige — atlas position (1025, 704), 64x64.
  let tankHullBeige = byName["tank_hull_beige"]
  /// plane_green — atlas position (1088, 704), 64x64.
  let planeGreen = byName["plane_green"]
  /// plane_gray — atlas position (1152, 704), 64x64.
  let planeGray = byName["plane_gray"]
  /// plane_ghost_a — atlas position (1088, 768), 64x64.
  let planeGhostA = byName["plane_ghost_a"]
  /// plane_ghost_b — atlas position (1152, 768), 64x64.
  let planeGhostB = byName["plane_ghost_b"]
  /// rocket_pod_single — atlas position (1408, 512), 64x64.
  let rocketPodSingle = byName["rocket_pod_single"]
  /// rocket_pod_dual — atlas position (1344, 512), 64x64.
  let rocketPodDual = byName["rocket_pod_dual"]
  /// rocket_small — atlas position (1344, 640), 64x64.
  let rocketSmall = byName["rocket_small"]
  /// rocket_large — atlas position (1408, 640), 64x64.
  let rocketLarge = byName["rocket_large"]
  /// coin_gold — atlas position (1216, 704), 64x64.
  let coinGold = byName["coin_gold"]
  /// effect_impact_burst — atlas position (1344, 0), 64x64.
  let effectImpactBurst = byName["effect_impact_burst"]
  /// effect_impact_ring — atlas position (1216, 0), 64x64.
  let effectImpactRing = byName["effect_impact_ring"]
  /// effect_impact_debris — atlas position (1280, 0), 64x64.
  let effectImpactDebris = byName["effect_impact_debris"]
  /// crosshair — atlas position (1408, 0), 64x64.
  let crosshair = byName["crosshair"]
  /// bush_small — atlas position (1024, 320), 64x64.
  let bushSmall = byName["bush_small"]
  /// rock_small — atlas position (1280, 320), 64x64.
  let rockSmall = byName["rock_small"]
  /// rock_medium — atlas position (1408, 320), 64x64.
  let rockMedium = byName["rock_medium"]
  /// rock_large — atlas position (1344, 320), 64x64.
  let rockLarge = byName["rock_large"]
  /// crate_metal_square — atlas position (1216, 448), 64x64.
  let crateMetalSquare = byName["crate_metal_square"]
  /// crate_metal_beveled — atlas position (1344, 448), 64x64.
  let crateMetalBeveled = byName["crate_metal_beveled"]
  /// crate_metal_diamond — atlas position (1408, 448), 64x64.
  let crateMetalDiamond = byName["crate_metal_diamond"]
  /// crate_metal_octagon — atlas position (1280, 448), 64x64.
  let crateMetalOctagon = byName["crate_metal_octagon"]
  /// container_large — atlas position (1344, 576), 64x64.
  let containerLarge = byName["container_large"]
  /// container_small — atlas position (1408, 576), 64x64.
  let containerSmall = byName["container_small"]
  /// tree_round — atlas position (1152, 320), 64x64.
  let treeRound = byName["tree_round"]
  /// tree_pine — atlas position (1216, 320), 64x64.
  let treePine = byName["tree_pine"]
  /// dirt_dot_on_grass — atlas position (192, 320), 64x64.
  let dirtDotOnGrass = byName["dirt_dot_on_grass"]
  /// dirt_circle_on_grass_top_left — atlas position (192, 0), 64x64.
  let dirtCircleOnGrassTL = byName["dirt_circle_on_grass_top_left"]
  /// dirt_circle_on_grass_top_right — atlas position (256, 0), 64x64.
  let dirtCircleOnGrassTR = byName["dirt_circle_on_grass_top_right"]
  /// dirt_circle_on_grass_bottom_left — atlas position (192, 64), 64x64.
  let dirtCircleOnGrassBL = byName["dirt_circle_on_grass_bottom_left"]
  /// dirt_circle_on_grass_bottom_right — atlas position (256, 64), 64x64.
  let dirtCircleOnGrassBR = byName["dirt_circle_on_grass_bottom_right"]
  /// dirt_patch_on_grass_top — atlas position (64, 192), 64x64.
  let dirtPatchOnGrassTop = byName["dirt_patch_on_grass_top"]
  /// dirt_patch_on_grass_bottom — atlas position (64, 320), 64x64.
  let dirtPatchOnGrassBottom = byName["dirt_patch_on_grass_bottom"]
  /// dirt_patch_on_grass_left — atlas position (0, 256), 64x64.
  let dirtPatchOnGrassLeft = byName["dirt_patch_on_grass_left"]
  /// dirt_patch_on_grass_right — atlas position (128, 256), 64x64.
  let dirtPatchOnGrassRight = byName["dirt_patch_on_grass_right"]
  /// dirt_patch_on_grass_top_left — atlas position (0, 192), 64x64.
  let dirtPatchOnGrassTopLeft = byName["dirt_patch_on_grass_top_left"]
  /// dirt_patch_on_grass_top_right — atlas position (128, 192), 64x64.
  let dirtPatchOnGrassTopRight = byName["dirt_patch_on_grass_top_right"]
  /// dirt_patch_on_grass_bottom_left — atlas position (0, 320), 64x64.
  let dirtPatchOnGrassBottomLeft = byName["dirt_patch_on_grass_bottom_left"]
  /// dirt_patch_on_grass_bottom_right — atlas position (128, 320), 64x64.
  let dirtPatchOnGrassBottomRight = byName["dirt_patch_on_grass_bottom_right"]
  /// dirt_patch_on_grass_center — atlas position (64, 256), 64x64.
  let dirtPatchOnGrassCenter = byName["dirt_patch_on_grass_center"]

  // ── Groups (curated in the generator) ──
  let groundGrass = [| grassFullA; grassFullB; grassFullC |]
  let groundDirt = [| dirtFullA; dirtFullB; dirtFullC |]

  let pathDirt = [|
    pathVerticalDirt
    pathHorizontalDirt
    pathEndUpDirt
    pathEndLeftDirt
  |]

  let effects = [| effectImpactBurst; effectImpactRing; effectImpactDebris |]

  let decoProps = [|
    bushSmall
    rockSmall
    rockMedium
    rockLarge
    crateMetalSquare
    crateMetalBeveled
    crateMetalDiamond
    crateMetalOctagon
    containerLarge
    containerSmall
    treeRound
    treePine
  |]

  let dirtBlends = [|
    dirtDotOnGrass
    dirtCircleOnGrassTL
    dirtCircleOnGrassTR
    dirtCircleOnGrassBL
    dirtCircleOnGrassBR
    dirtPatchOnGrassTop
    dirtPatchOnGrassBottom
    dirtPatchOnGrassLeft
    dirtPatchOnGrassRight
    dirtPatchOnGrassTopLeft
    dirtPatchOnGrassTopRight
    dirtPatchOnGrassBottomLeft
    dirtPatchOnGrassBottomRight
    dirtPatchOnGrassCenter
  |]

  let enemyHulls = [| tankHullGreen; tankHullBeige |]
  let enemyPlanes = [| planeGreen; planeGray; planeGhostA; planeGhostB |]
