<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Extensions.fs" />
    <Compile Include="World/Domain.fs" />
    <Compile Include="World/Tiles.fs" />
    <Compile Include="Diagnostics.fs" />
    <Compile Include="Telemetry.fs" />
    <Compile Include="World/Systems/Map.fs" />
    <Compile Include="World/Systems/Enemies.fs" />
    <Compile Include="World/Systems/Spawning.fs" />
    <Compile Include="World/Systems/Waves.fs" />
    <Compile Include="World/Systems/Economy.fs" />
    <Compile Include="World/Systems/Towers.fs" />
    <Compile Include="World/Systems/Projectiles.fs" />
    <Compile Include="World/Systems/Vfx.fs" />
    <Compile Include="World/Systems/Camera.fs" />
    <Compile Include="World/Projections.fs" />
    <Compile Include="World/World.fs" />
    <Compile Include="World/Router.fs" />
    <Compile Include="World/Frame.fs" />
    <Compile Include="Application.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Mibo\src\Mibo.Adaptive\Mibo.Adaptive.fsproj" />
  </ItemGroup>

</Project>
